
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1>Employee Settings</h1>
  <h3>Add Bank Details</h3>
  <div id="app-back-button">
      <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">

  

<form action="<?=BASE_PATH?>employee/addbankdetails" method="post">
<div style="margin: 0pt; padding: 0pt; display: inline;">
<input name="authenticity_token" value="nhTGd+k/mRvkMld6cK7gV4wLMuCJrQvRE3EsJlLoNFI=" type="hidden"></div>
      
      <div id="form-content">
        <div class="label-field-pair">
          <label for="category_name">Name</label>
          <div class="text-input-bg"> <input id="bank_field_name" name="bank_field[name]" size="30" type="text"> </div>
        </div>

        <div class="label-checkbox-pair">
          <label class="status" for="status">Status</label>
          <div id="radio-buttons">
            <input checked="checked" id="bank_field_status_true" name="bank_field[status]" value="true" type="radio">
            <label class="label_for_status" for="add_grade_status_true">Active</label>

            <input id="bank_field_status_false" name="bank_field[status]" value="false" type="radio">
            <label class="label_for_status" for="add_grade_status_false">Inactive</label>
          </div>
        </div>

        <div id="submit-button">
          <input name="commit" value="Create" type="submit">
        </div>
      </div>


</form>
    <div id="category-list">
      
<ul id="category-list">
  
    <p class="flash-msg">No bank details record found</p>
  
</ul>


    </div>

</div> </div>

      <div class="extender"></div>
    