<div id="content_wrapper">
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="" src="<?=IMAGES_URL?>HR/show_hr.png">
  <h1>Employee Settings</h1>
  <h3>Add grade</h3>
  <div id="app-back-button">
   <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

<form method="post" action="<?=BASE_PATH?>employee/addgrade"><div style="margin: 0pt; padding: 0pt; display: inline;"></div>
  

    
<div id="form-content">
    <div class="label-field-pair">
      <label for="grade_name">Name</label>
      <div class="text-input-bg"> <?php echo $this->form->name?>  </div>
    </div>

    <div class="label-field-pair">
      <label for="grade_priority">Priority</label>
      <div class="text-input-bg"> <?php echo $this->form->priority?>  </div>
    </div>

    <div class="label-field-pair">
      <label for="grade_priority">Max periods per day</label>
      <div class="text-input-bg"><?php echo $this->form->max_hours_day?>  </div>
    </div>

    <div class="label-field-pair">
      <label for="grade_priority">Max periods per week</label>
      <div class="text-input-bg"> <?php echo $this->form->max_hours_week?>  </div>
    </div>

    <div class="label-checkbox-pair">
      <label for="status" class="status">Status</label>
      <div id="radio-buttons">
     <?php echo $this->form->status?> 
    </div>
    </div>

    <div id="submit-button">
      <input type="submit" value="Create" name="commit">
    </div>
</div>

</form>
  <div id="grade-list">
    

<ul id="grade-list">
  
    <li class="listheading"><div class="grade-name"> Active Grades</div></li>
    
	 <? if(is_array($this->gradeList) && !empty($this->gradeList))
		{
		foreach($this->gradeList as $grade)
		{  ?>
	
	
      <li class="listodd">
        <div class="grade-name"><?=$grade['name']?> (<?=$grade['priority']?>)</div>
        <div class="grade-edit"><a href="<?=BASE_PATH?>employee/editgrade/id/<?=$grade['id']?>">Edit</a></div>
        <div class="grade-edit"><a onclick="return confirm('Are you sure?');" href="<?=BASE_PATH?>employee/deletegrade/id/<?=$grade['id']?>">Delete</a></div>
      </li>
    
      <? 
	 }
	 } ?> 
  
</ul>
  </div>

</div> </div>

      <div class="extender"></div>
    </div>