

     
      <div id="content"> 
<div id="content-header">
  <img alt="" src="<?=IMAGES_URL?>HR/show_hr.png">
  <h1><?=LNG_EMPLOYEE_SETTINGS?></h1>
  <h3><?=LNG_ADD_EMP_POSITION?></h3>
  <div id="app-back-button">
     <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

<form method="post" action="<?=BASE_PATH?>employee/addposition"><div style="margin: 0pt; padding: 0pt; display: inline;"></div>
  

    
 <div id="form-content" style="text-align:left;">
    <div class="label-field-pair">
      <label for="position_name"><?=LNG_NAME?></label>
      <div class="text-input-bg"> <?php echo $this->form->name ?> </div>
    </div>

   <div class="label-field-pair">
      <label for="category_name"><?=LNG_EMP_CATEGORY?></label>
      <div class="text-input-bg"><?php echo $this->form->employee_category_id ?></div>
    </div>

    <div class="label-checkbox-pair">
      <label for="status" class="status"><?=LNG_STATUS?></label>
      <div id="radio-buttons">
     <?php echo $this->form->status?> 
    </div>
    </div>

    <div id="submit-button">
      <input type="submit" value="<?=LNG_CREATE?>" name="commit">
    </div>
    </div>

</form>
  <div id="position-list">
 

<ul id="position-list">

  <li class="listheading"> <div class="position-name"><?=LNG_ACTIVE_POSITIONS?> </div> </li>
  
 <? if(is_array($this->positionList) && !empty($this->positionList))
		{
			
		foreach($this->positionList as $position)
		{  
			
			
		
		?>
	
  <li class="listodd">
    <div class="position-name"><?=$position['name']?> (<?=$position['catname']?>)</div>
    <div class="position-edit"><a href="<?=BASE_PATH?>employee/editposition/id/<?=$position['id']?>"><?=LNG_EDIT?></a></div>
    <div class="position-edit"><a onclick="return confirm('Are you sure?');" href="<?=BASE_PATH?>employee/deleteposition/id/<?=$position['id']?>"><?=LNG_DELETE?></a></div>
  </li>

    <? 
	 }
	 } ?> 
	 
	  
	  

</ul>

<ul id="position-list">

  <li class="listheading"> <div class="position-name"><?=LNG_INACTIVE_POSITIONS?> </div> </li>
  
 <? if(is_array($this->positionList2) && !empty($this->positionList2))
		{
		foreach($this->positionList2 as $position)
		{  
			
		?>
	
  <li class="listodd">
    <div class="position-name"><?=$position['name']?> (<?=$position['catname']?>))</div>
    <div class="position-edit"><a href="<?=BASE_PATH?>employee/editposition/id/<?=$position['id']?>"><?=LNG_EDIT?></a></div>
    <div class="position-edit"><a onclick="return confirm('Are you sure?');" href="<?=BASE_PATH?>employee/deleteposition/id/<?=$position['id']?>"><?=LNG_DELETE?></a></div>
  </li>

    <? 
	 }
	 } ?> 
	 
	  
	  

</ul>
  </div>

</div> </div>

      <div class="extender"></div>
