
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
   <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
<h1>Employee Admission</h1>
<h3>Step-4</h3>
<div id="app-back-button">
   <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
</div>
</div>

<div id="page-yield">


<p class="flash-msg"> Bank details saved </p>



<form action="<?=BASE_PATH?>employee/admission5/3" method="post"><div style="margin: 0pt; padding: 0pt; display: inline;"><input name="authenticity_token" value="nhTGd+k/mRvkMld6cK7gV4wLMuCJrQvRE3EsJlLoNFI=" type="hidden"></div>


    <div id="form-contents">
      <span class="span-sub-heading">Additional Details</span>
      <hr class="sub-heading">
        
        <div class="label-field-pair">
          <label>games</label>
          <div class="text-input-bg"><input id="employee_additional_details_1_additional_info" name="employee_additional_details[1][additional_info]" size="30" type="text"></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        
    </div>

  <div class="save-proceed-button">
    <input name="commit" value="Save &amp; Proceed" type="submit">
  </div>
</form>


</div>
 </div>

      <div class="extender"></div>
    