
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
 <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
<h1><?=LNG_EMP_ADMISSION?></h1>
<h3><?=LNG_STEP2?></h3>
<div id="app-back-button">
<a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
</div>
</div>

<div id="page-yield">


<p class="flash-msg"> <?=LNG_EMP_RECORD_SAVED?> </p>



<form action="<?=BASE_PATH?>employee/admission2/admission1Id/<?=$this->admission1Id?>" method="post">
<div style="margin: 0pt; padding: 0pt; display: inline;">
</div>
  
    <div id="form-contents" style="text-align:left;">
        <span class="span-sub-heading"><?=LNG_HOME_ADDRESS?></span>
    <hr class="sub-heading">

        <div class="label-field-pair">
          <label><?=LNG_LINE1?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_address_line1?><input type="hidden" name="admission1Id" id="admission1Id" value="<?=$this->admission1Id?>" />  </div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_LINE2?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_address_line2?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_CITY?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_city?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_STATE?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_state?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_COUNTRY?></label>
          <div class="text-input-bg">
		 <?php echo $this->form->employee_home_country_id?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_PIN?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_pin_code?></div>
          <div class="extender"></div>
        </div>
      <br>
        <span class="span-sub-heading"><?=LNG_OFFICE_ADDRESS?></span>
      <hr class="sub-heading">

        <div class="label-field-pair">
          <label><?=LNG_LINE1?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_address_line1?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_LINE2?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_address_line2?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_CITY?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_city?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_STATE?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_state?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_COUNTRY?></label>
          <div class="text-input-bg">
		  <?php echo $this->form->employee_office_country_id?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_PIN?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_pin_code?></div>
          <div class="extender"></div>
        </div>
      <br>
      </div>

  <div class="save-proceed-button">
    <input name="commit" value="<?=LNG_SAVE_AND_PROCEED?>" type="submit">
 	
	<input type="button" name="Finish" id="Finish" value="<?=LNG_SKIP_THIS_STEP?>" class="submit_button" onclick="skipthisstep();">
 
  </div>
  
</form>

</div> </div>

      <div class="extender"></div>
    