
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
    <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1><?=LNG_EMPLOYEE?></h1>
  <h3><?=LNG_EMPLOYEE_LIVING?></h3>
  <div id="app-back-button">
   <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">

  <div id="student-details">
<h4> <?=$this->detail['name']?> | Employee no : <?=$this->detail['code']?> | Department : <?=$this->detail['deptname']?> </h4>
  </div>

  <div class="extender"> </div>

  <div id="remove-student">
    <p>For employees leaving the school, use this option to remove them from the list of active employees and place them in the former employees list.</p>

    <form action="<?=BASE_PATH?>employee/changetoformer/profileid/<?=$this->detail['id']?>" method="post"><div style="margin: 0pt; padding: 0pt; display: inline;"><input name="authenticity_token" value="PiPGL2tWAVuJF36p/1+0ZpDyguIdM4CvSxplZxapZ/I=" type="hidden"></div>
      <div class="label-field-pair">
        <label for="remove_descr">Reason for leaving</label>
        <div class="text-input-bg"><input id="remove_status_description" name="status_description" size="30" type="text"></div>
      </div>

      <div id="submit-button">
	  <input  name="mode" value="former" type="hidden">
        <input class="submit_button" name="commit" value="Remove" type="submit">
      </div>

    </form>
  </div>

</div> </div>

      <div class="extender"></div>
    