
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
   <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1><?=LNG_EDIT_EMP_INFO?></h1>
  <h3><?=LNG_ADDRESS?></h3>
  <div id="app-back-button">
     <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

 <div id="page-yield">

  


  <form action="<?=BASE_PATH?>employee/edit2/profileid/<?=$this->profileid?>" method="post"><div style="margin:0;padding:0;display:inline"></div>
    
      <div id="form-contents">
        <span class="span-sub-heading"><?=LNG_HOME_ADDRESS?></span>
    <hr class="sub-heading">

        <div class="label-field-pair">
          <label><?=LNG_LINE1?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_address_line1?><input type="hidden" name="admission1Id" id="admission1Id" value="<?=$this->admission1Id?>" />  </div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_LINE2?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_address_line2?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_CITY?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_city?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_STATE?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_state?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_COUNTRY?></label>
          <div class="text-input-bg">
		 <?php echo $this->form->employee_home_country_id?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_PIN?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_pin_code?></div>
          <div class="extender"></div>
        </div>
      <br>
        <span class="span-sub-heading"><?=LNG_OFFICE_ADDRESS?></span>
      <hr class="sub-heading">

        <div class="label-field-pair">
          <label><?=LNG_LINE1?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_address_line1?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_LINE2?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_address_line2?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_CITY?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_city?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_STATE?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_state?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_COUNTRY?></label>
          <div class="text-input-bg">
		  <?php echo $this->form->employee_office_country_id?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label><?=LNG_PIN?></label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_pin_code?></div>
          <div class="extender"></div>
        </div>
      <br>
       
    </div>

    <div class="save-proceed-button">
      <input name="commit" value="<?=LNG_UPDATE?>" type="submit">
    </div>
  </form>

</div> </div>

      <div class="extender"></div>
    