
<div id="side_bar">
<div id="sidebar_news_area">
</div>
</div>
<div id="content">
<div id="content-header">
<img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
<h1>Edit employee information</h1>
<h3>Contact</h3>
<div id="app-back-button">
<a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313586643" border="0"></a>
</div>
</div>
<div id="page-yield">
<form action="<?=BASE_PATH?>employee/editcontact/profileid/<?=$this->profileid?>" method="post"><div style="margin:0;padding:0;display:inline"></div>
<span class="span-sub-heading">Contact Details</span>
 <hr class="sub-heading">

        <div class="label-field-pair">
          <label>Office phone1</label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_phone1?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label>Office phone2</label>
          <div class="text-input-bg"><?php echo $this->form->employee_office_phone2?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label>Mobile</label>
          <div class="text-input-bg"><?php echo $this->form->employee_mobile_phone?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label>Home phone</label>
          <div class="text-input-bg"><?php echo $this->form->employee_home_phone?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label>Email</label>
          <div class="text-input-bg"><?php echo $this->form->employee_email?></div>
          <div class="extender"></div>
        </div>
        <hr class="label-underline">
        <div class="label-field-pair">
          <label>FAX</label>
          <div class="text-input-bg"><?php echo $this->form->employee_fax?></div>
          <div class="extender"></div>
        </div>
<div class="save-proceed-button">
<input name="commit" value="Update" type="submit">
</div>
</form>
</div> </div>
<div class="extender"></div>
