
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1>Employee Settings</h1>
  <h3>Edit department</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">

<form action="<?=BASE_PATH?>employee/edit_department/id/<?=$this->depId?>" method="post"><div style="margin: 0pt; padding: 0pt; display: inline;"></div>
  
    

    
<div id="form-content">
    <div class="label-field-pair">
      <label for="department_name">Name</label>
      <div class="text-input-bg"><?php echo $this->form->name?> </div>
    </div>

    <div class="label-field-pair">
      <label for="department_code">Dept. code</label>
      <div class="text-input-bg"> <?php echo $this->form->code?>  </div>
    </div>

    <div class="label-checkbox-pair">
      <label class="status" for="status">Status</label>
      <div id="radio-buttons">
      <?php echo $this->form->status?>
		<?php echo $this->form->id?>
    </div>
    </div>

    <div id="submit-button">
      <input name="commit" value="Update" type="submit">
    </div>
</div>

</form>

</div> </div>

      <div class="extender"></div>
    