
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
   <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1>Employee Settings</h1>
  <h3>Edit Additional Details</h3>
  <div id="app-back-button">
     <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">

  

<form action="<?=BASE_PATH?>employee/editadditionaldetails/1" method="post"><div style="margin: 0pt; padding: 0pt; display: inline;"><input name="authenticity_token" value="nhTGd+k/mRvkMld6cK7gV4wLMuCJrQvRE3EsJlLoNFI=" type="hidden"></div>
      
      <div id="form-content">
        <div class="label-field-pair">
          <label for="category_name">Name</label>
          <div class="text-input-bg"> 
		  <input id="additional_details_name" name="additional_details[name]" size="30" type="text"> </div>
        </div>

        <div class="label-checkbox-pair">
          <label class="status" for="status">Status</label>
          <div id="radio-buttons">
            <input checked="checked" id="additional_details_status_true" name="additional_details[status]" value="true" type="radio">
            <label class="label_for_status" for="add_grade_status_true">Active</label>

            <input id="additional_details_status_false" name="additional_details[status]" value="false" type="radio">
            <label class="label_for_status" for="add_grade_status_false">Inactive</label>
          </div>
        </div>

        <div id="submit-button">
          <input name="commit" value="Update" type="submit">
        </div>
      </div>


</form>
</div> </div>

      <div class="extender"></div>
    