
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 

<div id="content-header">
  <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1>User Privileges</h1>
  <h3>Set Privilege</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>



<div class="label_field_pair"><label>Set privileges for </label></div>
<div id="list_content">
  <div id="list">
    <div class="sel-list">
      Select: <a href="#" onclick="$$('input.abc').each(function(checkbox) { checkbox.checked = true; });; return false;">All</a>,
      <a href="#" onclick="$$('input.abc').each(function(checkbox) { checkbox.checked = false; });; return false;">None</a>
    </div>


    <form action="<?=BASE_PATH?>employee/editprivilege/userId/2" method="post">
	<div style="margin: 0pt; padding: 0pt; display: inline;">
	</div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="1" type="checkbox">
              </label><div class="att_list_names"> Examination control </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="2" type="checkbox">
              </label><div class="att_list_names"> Enter results </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="3" type="checkbox">
              </label><div class="att_list_names"> View results </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="4" type="checkbox">
              </label><div class="att_list_names"> Admission </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="5" type="checkbox">
              </label><div class="att_list_names"> Students control </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="6" type="checkbox">
              </label><div class="att_list_names"> Manage news </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="7" type="checkbox">
              </label><div class="att_list_names"> Manage timetable </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="8" type="checkbox">
              </label><div class="att_list_names"> Student attendance view </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="9" type="checkbox">
              </label><div class="att_list_names"> Hr basics </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="10" type="checkbox">
              </label><div class="att_list_names"> Add new class </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="11" type="checkbox">
              </label><div class="att_list_names"> Subject master </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="12" type="checkbox">
              </label><div class="att_list_names"> Event management </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="13" type="checkbox">
              </label><div class="att_list_names"> General settings </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="14" type="checkbox">
              </label><div class="att_list_names"> Finance control </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="15" type="checkbox">
              </label><div class="att_list_names"> Timetable view </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="16" type="checkbox">
              </label><div class="att_list_names"> Student attendance register </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="17" type="checkbox">
              </label><div class="att_list_names"> Employee attendance </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="18" type="checkbox">
              </label><div class="att_list_names"> Payslip powers </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listodd"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="19" type="checkbox">
              </label><div class="att_list_names"> Employee search </div> 
          </li></div>
      
        
        
        
        
        <div class="name_listeven"><li>
            <label><input class="abc" id="user_privilege_ids_" name="user[privilege_ids][]" value="20" type="checkbox">
              </label><div class="att_list_names"> Sms management </div> 
          </li></div>
      
      <div class="user_submit_button1">
        <input name="commit" value="Update" type="submit">
      </div>
    </form>
  </div>
</div> </div>

      <div class="extender"></div>
    