<div id="content_wrapper">
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="" src="<?=IMAGES_URL?>HR/show_hr.png">
  <h1><?=LNG_EMPLOYEE_MANAGEMENT?></h1>
  <h3><?=LNG_MANAGE_ALL_EMPLOYEE?> </h3>
  <div id="app-back-button">
     <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">
  <div id="box">
  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>employee/admission1"><?=LNG_EMP_ADMISSION?></a></div>
    <div class="link-descr"><?=LNG_EMP_ADMISSION_FORM?></div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>employee/subjectassignment"><?=LNG_EMP_SUBJECT_ASSOCIATION?></a></div>
    <div class="link-descr"><?=LNG_EMP_TEXT5?></div>
  </div>
  
  <?php /*?><div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>employee/classassignment"><?=LNG_EMP_CLASS_ASSOCIATION?></a></div>
    <div class="link-descr"><?=LNG_EMP_TEXT6?></div>
  </div><?php */?>
  </div>

</div> </div>

      <div class="extender"></div>
    </div>