
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="" src="<?=IMAGES_URL?>HR/show_hr.png">
  <h1><?=LNG_MANAGE_EMPLOYEE?></h1>
  <h3><?=LNG_TEACHER?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>


<div id="page-yield">
  
  <div id="box">
    
      <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>employee/settings"><?=LNG_SETTINGS?></a></div>
        <div class="link-descr"><?=LNG_EMPLOYEE_SETTINGS?></div>
      </div>
    
    
      <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>employee/employeemanagement"><?=LNG_EMPLOYEE_MANAGEMENT?></a></div>
        <div class="link-descr"> <?=LNG_MANAGE_ALL_EMPLOYEE?> </div>
      </div>
    
	  
	   <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>employee/search"><?=LNG_EMPLOYEE_SEARCH?></a></div>
        <div class="link-descr"><?=LNG_SEARCH_FOR_EMPLOYEES?></div>
      </div>
	  
    <?php /*?>  <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>employee/employeeattendance">Employee Leave Management </a></div>
        <div class="link-descr">Manage all employee attendance and leaves</div>
      </div>
	  
      <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>employee/addpayslipcategory">Create Payslip</a></div>
        <div class="link-descr">Create employee monthly payslips</div>
      </div>
    
	<div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>employee/viewall"><?=LNG_EMPLOYEE_LIST?></a></div>
        <div class="link-descr"><?=LNG_SEARCH_FOR_EMPLOYEES?></div>
      </div>
     
    
    
    <div class="link-box">
      <div class="link-heading"><a href="<?=BASE_PATH?>employee/departmentpayslip">Employee payslip</a></div>
      <div class="link-descr">View department wise payslip</div>
    </div><?php */?>
    
  </div>
</div>
 </div>

      <div class="extender"></div>
