<link href="<?=CSS_URL?>employee/remove.css?1313586643" media="screen" rel="stylesheet" type="text/css"/>
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1><?=LNG_EMPLOYEE?></h1>
  <h3><?=LNG_EMPLOYEE_REMOVE?></h3>
  <div id="app-back-button">
     <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">

  <div id="student-details">
    <h4> <?=$this->detail['name']?> | Employee no : <?=$this->detail['code']?> | Department : <?=$this->detail['deptname']?> </h4>
  </div>

  <div class="extender"> </div>
  <div class="box">
  
  <div class="link-box">
    <div class="link-heading"> <a href="<?=BASE_PATH?>employee/changetoformer/profileid/<?=$this->profileid?>">Employee leaving School/Institution</a> </div>
    <div class="link-descr">For employee leaving the Institution, use this option to remove them from the list of active employee and place them in the former employees list.</div>
  </div>
  
  <div class="link-box">
    <div class="link-heading"> <a href="<?=BASE_PATH?>employee/delete/profileid/<?=$this->profileid?>" onclick="return confirm('This will also unassign employee from all his current subjects , Do you want to proceed ?');">Remove employee records</a> </div>
    <div class="link-descr">Completely delete employee's records from the Institution's databases. Use this option only if you created the employee record by accident and want to remove it completely.</div>
  </div>
  </div>
    <!--

  <div id="remove-student">
    <h4><a href="/employee/remove/3">Student leaving school</a></h4>
    <p>For students leaving the school, use this option to remove them from the list of active students and place them in the former students list.</p>
    <form action="/employee/remove/3" method="post"><div style="margin:0;padding:0;display:inline"><input name="authenticity_token" type="hidden" value="PiPGL2tWAVuJF36p/1+0ZpDyguIdM4CvSxplZxapZ/I=" /></div>
      <div class="label-field-pair">
        <label for="remove_descr">Reason for leaving</label>
        <div class="text-input-bg"><input id="remove_description" name="remove[description]" size="30" type="text" /></div>
      </div>
      <div class="extender"> </div>
      <input src="/images/buttons/remove.png?<?=UPDATE_KEY?>" type="image" />
    </form>
  </div>

  <div id="delete-student">
    <h4>Delete student</h4>
    <p>Completely delete student's records from the school's databases. Use this option only if you created the student record by accident and want to remove it completely.</p>

    <p class="warning">(Warning: All records will be deleted for the student and cannot be recovered.)</p>
    <a href="/employee/destroy/3" onclick="return confirm('Are you completely sure?');"><img alt="Delete" border="0" src="/images/buttons/delete.png?<?=UPDATE_KEY?>" /></a>
  </div>
    -->

</div> </div>

      <div class="extender"></div>
    