

      <div id="side_bar">

        <div id="sidebar_news_area">
 </div>
      </div>
      <div id="content"> 
<div id="content-header">

  <img alt="" src="<?=IMAGES_URL?>HR/show_hr.png">

  <h1><?=LNG_SETTINGS?></h1>

  <h3><?=LNG_EMPLOYEE_SETTINGS?></h3>

  <div id="app-back-button">

     <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>

  </div>

</div>



<div id="page-yield">

  <div id="box">

    <div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>employee/addcategory"><?=LNG_ADD_EMP_CATEGORY?></a></div>

      <div class="link-descr"><?=LNG_EMP_TEXT2?></div>

    </div>



    <div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>employee/addposition"><?=LNG_ADD_EMP_POSITION?></a></div>

      <div class="link-descr"><?=LNG_EMP_TEXT3?></div>

    </div>



    <div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>employee/adddepartment"><?=LNG_ADD_EMP_DEPT?></a></div>

      <div class="link-descr"><?=LNG_EMP_TEXT4?></div>

    </div>



    <?php /*?><div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>employee/addgrade">Add employee grade</a></div>

      <div class="link-descr">Add and edit employee grade.</div>

    </div><?php */?>


<?php /*?>
    <div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>payroll/addcategory">Add payroll category</a></div>

      <div class="link-descr">Add and edit employee payroll category.</div>

    </div>



    <div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>employee/addbankdetails">Add bank details</a></div>

      <div class="link-descr">Add and edit bank details.</div>

    </div>



    <div class="link-box">

      <div class="link-heading"><a href="<?=BASE_PATH?>employee/addadditionaldetails">Add additional details</a></div>

      <div class="link-descr">Add and edit additional details for employee admission forms.</div>

    </div>



   <!-- <div class="link-box">

      <div class="link-heading"><a href="/employee/">Payslip Settings</a></div>

      <div class="link-descr">Creates payslip approve power for finance manager.</div>

    </div>

  </div> --><?php */?>

   <div class="extender"></div>

  </div>

</div>

 </div>



      <div class="extender"></div>

