<link href="<?=CSS_URL?>employee/view_all.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
   <img src="<?=IMAGES_URL?>HR/show_hr.png" alt="">
  <h1><?=LNG_VIEW_ALL?></h1>
  <h3><?=LNG_VIEW_ALL_S?></h3>
  <div id="app-back-button">
  <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">
       <div class="label-field-pair">
  <label><?=LNG_SELECT_A_DEPARTMENT?> </label>
<div class="text-input-bg"><select id="subject_assignment_department_id" name="subject_assignment[department_id]" onchange="getajax('<?=BASE_PATH?>employee/employeeslist', '?department_id='+this.value,'employee_list')"><option value=""><?=LNG_SELECT_DEPARTMENT?></option>
<?

	foreach($this->deptlist as $deptlist) { ?>
	<option value="<?=$deptlist['id']?>"><?=$deptlist['name']?></option>
	<? 
	}
	?>
	</select>
  </div>
       </div>
  <div class="extender"></div>
<div id="employee_list">
</div>
</div> </div>

      <div class="extender"></div>
    