<?
global $mySession;
?>
<link href="<?=CSS_URL?>exam_groups/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />

      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>examination/show_exam.png" alt="Exam">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_EXAM_GROUPS?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>
	<div id="inner-tab-menu">
		  <ul>
		  <li><a href="<?=BASE_PATH?>exam/updateexamform/batchid/<?=$this->batchid?>/"><?=LNG_NEW?></a></li>
	<? if($mySession->user['usertype']=='S') { ?>		
			  <?php /*?><li><a href="<?=BASE_PATH?>examgroups/new/batchid/<?=$this->batchid?>/"><?=LNG_NEW?></a></li><?php */?>			  
		  	<li><a href="<?=BASE_PATH?>exam/grouping/batchid/<?=$this->batchid?>"><?=LNG_CONNECT_EXAMS?></a></li>	
	<? } ?>
		  </ul>
		</div>
<div id="page-yield">

  <div class="label-field-pair">
   <label><?=LNG_SELECT_A_BATCH?><?=LNG_SEPERATOR_1?></label>
 <div class="text-input-bg">
  <select onchange="document.location='<?=BASE_PATH?>examgroups/index/batchid/'+this.value" name="sel_batch_id" id="sel_batch_id">		
		<? 
		foreach($this->cblist as $cblist) {?>
		<option value="<?=$cblist['id']?>" <? if(@$this->batchid==$cblist['id']) { ?> selected="selected"<? } ?>><?=$cblist['grade_name']?> - <?=$cblist['name']?></option>
		<? } ?>
	</select>
  <img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
</div></div>


    <?php /*?><div class="bread_crumb">
    <a href="<?=BASE_PATH?>grades"><?=LNG_GRADES?></a> &raquo;
    <a href="<?=BASE_PATH?>grades/show/gradeid/<?=$this->blist['grade_id']?>"><?=$this->blist['grade_name']?></a> &raquo;
    <a href="<?=BASE_PATH?>batches/show/gradeid/<?=$this->blist['grade_id']?>/batchid/<?=$this->blist['id']?>"><?=LNG_BATCH?> <?=$this->blist['name']?></a> &raquo;
      <?=LNG_EXAMS?>
    </div><?php */?>

<?
  tframe_pre();
  ?>

    <table id="listing" width="100%">
      <tbody><tr class="tr-head">
        <td><?=LNG_EXAM_NAME?></td>
        <td> <?=LNG_ACTION?></td>
      </tr>
      <? $i=0;
	  foreach($this->elist as $elist) { 
	  $m=$i%2; 
		if($m==0)
		{
			$class="tr-even";	
		}else{
			$class="tr-odd";	
		}
		?>
      
        <tr class="<?=$class?>">
          <td class="col-2">

            <a href="<?=BASE_PATH?>examgroups/show/examgroupid/<?=$elist['id']?>"><?=$elist['name']?></a>
            <span><small>
                <a href="<?=BASE_PATH?>examgroups/index/batchid/<?=$this->batchid?>" onclick="if (confirm('Are you sure?')) { var f = document.createElement('form'); f.style.display = 'none'; this.parentNode.appendChild(f); f.method = 'POST'; f.action = this.href;var m = document.createElement('input'); m.setAttribute('type', 'hidden'); m.setAttribute('name', 'mode'); m.setAttribute('value', 'delete'); f.appendChild(m);var s = document.createElement('input'); s.setAttribute('type', 'hidden'); s.setAttribute('name', 'examgroupid'); s.setAttribute('value', '<?=$elist['id']?>'); f.appendChild(s);f.submit(); };return false;"><?=LNG_DELETE?></a>
                <s></s>
              </small></span>
          </td>
          <td class="col-2" id="examstatus_td_<?=$elist['id']?>">
		  <small>
     <? if($mySession->user['usertype']=='S'){ ?>
			  <? if($elist['result_published']==1) { ?>
                <?=LNG_EXAM_RESULT_PUBLISHED?>
              <? } elseif($elist['is_published']==1) { ?>
			  <?=LNG_SCHEDULED_PUBLISHED?>
<a onclick="getajax('<?=BASE_PATH?>exam/publish/examgroupid/<?=$elist['id']?>?status=result', '','publish-notice-<?=$elist['id']?>','2')" href="#"><?=LNG_PUBLISH_EXAM_RESULT?></a>
	<? }else{
			?>
				<a href="#" onclick="getajax('<?=BASE_PATH?>exam/publish/examgroupid/<?=$elist['id']?>?status=schedule', '','publish-notice-<?=$elist['id']?>','2')"><?=LNG_PUBLISH_EXAM_SCHEDULE?></a>
			<?
			} ?>
			<? } else { ?>
				  <? if($elist['result_published']==1) { ?>
					<?=LNG_EXAM_RESULT_PUBLISHED?>
				  <? } elseif($elist['is_published']==1) { ?>
				  <?=LNG_SCHEDULED_PUBLISHED?>
		
				<? }else{
				?>
					<?=LNG_EXAM_SCHEDULE_NOT_PUBLISHED?>
				<?
				} ?>
			   
			  <? } ?>
              <span id="publish-notice-<?=$elist['id']?>"></span>
              
            </small> </td>
        </tr>
      <? } ?>
       
      
    </tbody></table>
<?
  tframe_post();
  ?>
    <div class="extender"></div>

</div> </div>

      <div class="extender"></div>
    