<script>
function gotoset()
{
	getajax('<?=BASE_PATH?>attendances/manageattendancesregister','?batch_id='+document.getElementById("batch_id").value,'register');
}
</script>
<div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>attendence/attendence.png">
  <h1><?=LNG_ATTENDANCE?></h1>
  <h3><?=LNG_ATTENDANCE_REGISTER?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>


<div id="page-yield">
<div class="label-field-pair">
  <label><?=LNG_SELECT_A_BATCH?> </label>
  <div class="text-input-bg">
    <select onchange="getajax('<?=BASE_PATH?>attendances/manageattendancesregister','?batch_id='+this.value,'register');" name="batch[id]" id="batch_id">
      <option value=""><?=LNG_SELECT_A_BATCH?></option>
      <?
		foreach($this->cblist as $cblist) { ?>
		<option value="<?=$cblist['id']?>"><?=$cblist['grade_name']?> - <?=$cblist['name']?></option>
	  <? } ?>
    </select>
    </div>
<img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
</div>



<div id="subjects"></div>
<div id="register"></div>
<div style="display: none;" id="modal-box"></div>
</div> </div>

      <div class="extender"></div>
