<?
global $mySession;
$db = new Db();
?>
<link href="<?=CSS_URL?>student/guardians.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_NOTES?></h1>
  <h3><?=LNG_NOTES_ABOUT_STUDENT?></h3>
  <div id="app-back-button">
      <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="inner-tab-menu">
  <ul>
    <li style="width:120px;"><a href="<?=BASE_PATH?>student/profile/studentid/<?=$this->studentdetail['id']?>"><?=LNG_STUDENT_PROFILE?></a></li>
    
     <?php /*?> <li><a href="<?=BASE_PATH?>student/addguardian/studentid/<?=$this->studentdetail['id']?>">Add guardian</a></li><?php */?>
    
  </ul>
</div>

<div id="page-yield">

  

  <div id="student_profile_heading">



    <div id="student_main_info">
      <span class="name"> <? echo $this->studentdetail['stname']; ?>  </span>
      <span class="course"> <?=LNG_GRADE?> <?=$this->studentdetail['grade_name']?>; <?=LNG_BATCH?>: <?=$this->studentdetail['batchname']?> </span>&nbsp;
      <span class="adm"> <?=LNG_ADM_NO?> : <? echo $this->studentdetail['admission_no'];?> </span>
    </div>

    <div class="extender"> </div>

  </div>	
	
	<div id="reply-form" align="center" >
      <form method="post" action="<?=BASE_PATH?>student/addnote/studentid/<?=$this->studentdetail['id']?>">
        <input type="hidden" name="mode" value="addnote" />
        <div class="message" style="width:700px;">
	        <div class="label-field-pair">           
				<div class="text-area-bg">
					<textarea name="usernote" id="usernote" style="width:550px;"></textarea>
				</div>
    	    </div>
          <div class="extender"></div>
          <div>
			<input type="submit" value="<?=LNG_ADD_NOTE?>" name="commit" class="button">
        </div>
        </div>
        
      </form>
    </div>


</div></div>

      <div class="extender"></div>
    