<link href="<?=CSS_URL?>student/advanced_search.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      

      <div id="content"> 

<div id="content-header">

  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">

  <h1><?=LNG_STUDENT?></h1>

  <h3><?=LNG_ADVANCE_SEARCH?></h3>

  <div id="app-back-button">

    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>

  </div>

</div>
<div id="inner-tab-menu">
  <ul>
   	<li style="width:125px;"><a href="<?=BASE_PATH?>student/viewall"><?=LNG_SIMPLE_SEARCH?></a></li>
  </ul>
</div>
<div id="page-yield">

  <div id="search-form" style="text-align:left;">

    <form method="get" action="<?=BASE_PATH?>student/advancesearchlist">

	<div><input type="hidden" name="search[order]" id="search_order"></div>

       <div class="label-field-pair">
			<label for="student_admission_no"><?=LNG_ID?></label>
			<div class="text-input-bg"><?php echo $this->form->student_passport_no?></div>
		</div>
	  
	  <div class="label-field-pair">
        <label for="student_grade"><?=LNG_TITLE?> </label>
        <div class="text-input-bg"><?php echo $this->form->title?></div>
      </div>
	  
	  <div class="label-field-pair">

        <label for="name"><?=LNG_NAME?></label>

        <div class="text-input-bg"><?php echo $this->form->first_name?></div>

      </div>

      <div class="label-field-pair">
        <label for="student_admission_no"><?=LNG_ADM_NO?></label>
        <div class="text-input-bg"><?php echo $this->form->student_admission_no?></div>
      </div>
	  <div class="label-field-pair">

        <label for="student_class"><?=LNG_SESSION_START_YEAR?></label>
        <div class="text-input-bg"><select name="search_year" id="search_year" onchange="if(document.getElementById('search_gradeid').value!='') { getajax('<?=BASE_PATH?>student/batchlistcombo/','?gradeid='+document.getElementById('search_gradeid').value+'&search_year='+this.value,'batchlist'); }">
	<? 
	$yy = date("Y");
	for($i=$yy; $i > ($yy-2); $i--){ ?>
	<option value="<?=$i?>"><?=$i?></option>
	<? } ?>
	
	</select></div>
      </div>
      <div class="label-field-pair">

        <label for="student_class"><?=LNG_SELECT_A_GRADE?></label>
        <div class="text-input-bg"><select onchange="getajax('<?=BASE_PATH?>student/batchlistcombo/','?gradeid='+this.value+'&search_year='+document.getElementById('search_year').value,'batchlist');" name="search_gradeid" id="search_gradeid">
	<option value=""><?=LNG_SELECT_A_GRADE?></option>
	<? if(isset($this->batchlist) && count($this->batchlist) > 0) { ?>
		<? foreach($this->batchlist as $batchlist) { ?>
			<option value="<?=$batchlist['id']?>"><?=$batchlist['grade_name']?></option>
		<? } ?>
	<? } ?>
	</select></div>
      </div>
	  <div class="label-field-pair">

        <label for="student_class"><?=LNG_SELECT_A_BATCH?></label>
        <div class="text-input-bg" id="batchlist"><select name="search_batchid" id="search_batchid">
	<option value=""><?=LNG_SELECT_A_BATCH?></option>
	
	</select></div>
      </div>
      <div class="label-field-pair">
        <label for="student_category"><?=LNG_NATIONALITY?></label>
        <div class="text-input-bg"><?php echo $this->form->student_nationality?></div>
      </div>
 	<div class="label-field-pair">
        <label for="student_category"><?=LNG_SELECT_A_RELIGION?></label>
        <div class="text-input-bg">
		<select name="search_religion" id="search_religion">
		<option value=""><?=LNG_SELECT_A_RELIGION?></option>
		<option value="1">Islam</option>
		<option value="2">Hindu</option>
		</select>
	</div>
      </div>

      <div class="label-field-pair">
        <label for="student_country"><?=LNG_ADDRESS?></label>
        <div class="text-input-bg"><?php echo $this->form->student_address_line1?></div>
      </div>



      <div class="label-field-pair">
        <label for="student_grade"><?=LNG_ADMISSION_DATE?></label>
        <div class="text-input-bg">
	  <div id="doa_year"><div style="float:left"><?php echo $this->form->admission_date?></div><div style="float:left; padding-left:5px; padding-top:10px"><img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('admission_date'), {year_range:[<?=date('Y',mktime(0,0,0,date('m'),date('d'),date('Y')-40))?>, <?=date('Y',mktime(0,0,0,date('m'),date('d'),date('Y')))?>]} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
	  <div style="float:left; padding-top:5px">&nbsp;To&nbsp;</div>
	  <div style="float:left"><?php echo $this->form->admission_date_to?></div><div style="float:left; padding-left:5px; padding-top:10px"><img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('admission_date_to'), {year_range:[<?=date('Y',mktime(0,0,0,date('m'),date('d'),date('Y')-40))?>, <?=date('Y',mktime(0,0,0,date('m'),date('d'),date('Y')))?>]} );" class="calendar_date_select_popup_icon" alt="Calendar"></div> </div>
          <div id="doa_year_hidden"></div>
        </div>

      </div>

      <div class="label-field-pair">
        <label for="student_birth_date"><?=LNG_BIRTH_DATE?></label>
        <div class="text-input-bg">
          <div id="dob_year"><div style="float:left"><?php echo $this->form->date_of_birth?></div><div style="float:left; padding-left:5px; padding-top:10px"><img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('date_of_birth'), {year_range:[1971, 2011]} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
		  <div style="float:left; padding-top:5px">&nbsp;To&nbsp;</div>
		  <div style="float:left"><?php echo $this->form->date_of_birth_to?></div><div style="float:left; padding-left:5px; padding-top:10px"><img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('date_of_birth_to'), {year_range:[1971, 2011]} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
		  </div>
          <div id="dob_year_hidden"></div>
        </div>

      </div>

    

      <input type="submit" value="Search" name="commit" id="search_submit" class="submit">

    </form>

  </div>

  



</div> </div>



      <div class="extender"></div>

