 <link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
 <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_STUDENT_DETAILS?></h1>
  <h3><?=LNG_ADVANCE_SEARCH_DETAILS?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li style="width:125px;"><a href="<?=BASE_PATH?>student/advancedsearch"><?=LNG_ADVANCE_SEARCH?></a></li>
	<li style="width:125px;"><a href="<?=BASE_PATH?>student/viewall"><?=LNG_SIMPLE_SEARCH?></a></li>
  </ul>
</div>
<div id="page-yield">
<div class="students-table">
<form method="post" action="">
<? if(isset($this->studentlist) && count($this->studentlist) > 0) { ?>
  <table align="center" cellpadding="1" cellspacing="1" width="100%">
    <tbody><tr class="tr-head">
      
      <td>
       <?=LNG_NAME?>
      </td>
      <td>
        <?=LNG_ADM_NO?>
      </td>
      <td>
		<?=LNG_BATCH?>
      </td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <? $i=1; 
  foreach($this->studentlist as $studentlist) {
   $m=$i%2; 
		if($m==0)
		{
			$class="tr-even";	
		}else{
			$class="tr-odd";	
		}
   ?>
      <tr class="<? echo $class; ?>">
       

        <td class="col-2">
          <a href="<?=BASE_PATH?>student/profile/studentid/<?=$studentlist['id']?>"><?=$studentlist['sname']?></a>
        </td>

        <td class="col-3">
          <?=str_pad($studentlist['admission_no'],6,0,STR_PAD_LEFT)?>
        </td>

        <td class="col-4">
          <?=$studentlist['gname']?>-<?=$studentlist['bname']?>
        </td>
      </tr>
    <? $i++; } ?>
     
    
  </tbody></table>
  <? }else {
	?>
		<p class="flash-msg"> <?=LNG_NO_STUDENTS_IN_SELECTED_BATCH?> </p>
	<?
}
	?>
		<div><input type="hidden" name="wherecondition" id="wherecondition" value="<?=$this->wherecondition?>"></div>
		<div class="submit-button">
			<input type="button" class="submit-button" style="float:right; margin-right:20px;" name="commit" onclick="this.form.action='<?=BASE_PATH?>student/exportxls/'; this.form.submit()" value="<?=LNG_EXPORT?>">
		</div>
	</form>
</div>
</div> </div>

      <div class="extender"></div>