<link href="<?=CSS_URL?>student/delete.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>admission/admission_page_logo.jpg">
  <h1>Students</h1>
  <h3>Remove student</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>

<div id="page-yield">

  <div id="delete-student" style="text-align:left;">
    <h4><?=LNG_DELETE_STUDENT?></h4>
    <p><?=LNG_DELETE_STUDENT_TEXT_1?></p>

    <p class="warning"><?=LNG_DELETE_STUDENT_TEXT_2?></p>
    <a href="<?=BASE_PATH?>student/destroy/studentid/<?=$this->studentid?>" class="delete-button" onclick="return confirm('Are you completely sure?');"><?=LNG_DELETE?></a>
  </div>

</div> </div>

      <div class="extender"></div>
    