<?

	$db= new Db();

	global $mySession;

	?>

<link href="<?=CSS_URL?>finance/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />



<?

if($this->mode==0) { ?>

<label class="head_label">Add new fees for <span> <?=$this->stu_info[0]['stname']?>

</span></label>
<form action="" method="post" onsubmit="getajax('<?=BASE_PATH?>student/feescreatetemplate/','?'+Form.serialize(this),'modal-box','2'); return false">

    <input id="studentid" name="studentid" value="<?=$this->studentid?>" type="hidden">

	<input id="mode" name="mode" value="add" type="hidden">
<div id="ajax_create">
<div style="height:180px"><table width="100%" id="smaltable">

  <tbody><tr class="tr-head">

    <td width="50">#</td>

	<td width="153">Name</td>

    <td width="57">Inst</td>

    <td width="695">Inst. Amount</td>

	

  </tr>

  	<? 

		$i=1;

	foreach($this->slist as $slist) {

		$m=$i%2; 

		if($m==0)

		{

			$class="tr-even";	

		}else{

			$class="tr-odd";	

		}

	 ?>

   <tr class="<? echo $class; ?>" id="class-timing-1">

      <td class="col-1" style="30px"><input type="checkbox"  name="chk[]" value="b_<?=$slist['id']?>" /></td>

	  <td class="col-2" style="300px"><?=$slist['catname']?></td>

      <td class="col-3" style="70px"><?=$slist['noofinst']?></td>

      <? 

	  

	  $qry="select *, DATE_FORMAT(dueon, '%M %d, %Y') as dueondt from `fees_structuredetail` where fsid='".$slist['id']."'"; 

	  $installment=$db->runQuery("$qry");

	  ?>

      <td class="col-4" style="width:300px;"><? 
	  $insinfo = array();
	  foreach($installment as $inst) {
	  	$insinfo[] = $inst['inst'];
	  }
	  echo implode(", ",$insinfo);?>
	  </td>

	  

    </tr>

	<? $i++; } 

	?>

	</tbody></table></div><input class="submit-button MB_focusable" id="submit" name="commit" value="Save" type="submit"></div>

<?

} elseif($this->mode==1) { 
$string = '<tbody>
<tr class="tr-head"> 
   <td>&nbsp;</td>
	<td>Name</td>
    <td>No. of Installments</td>
    <td>Installment Amount</td>

  </tr>';

  	
		$i=1;
	foreach($this->slist as $slist){
		$m=$i%2;
		if($m==0)
		{
			$class="tr-even";
		}else{
			$class="tr-odd";
		}
	 
$string .= '<tr class="'.$class.'" id="class-timing-1">

   	  <td class="col-1" style="30px"><input type="checkbox"  name="chk[]" value="b_'.$slist['id'].'" checked="checked" /></td>   
	  <td class="col-3" style="300px">'.$slist['catname'].'</td>
      <td class="col-2" style="70px">'.$slist['noofinst'].'</td>';

     
	  $qry="select *, DATE_FORMAT(dueon, '%M %d, %Y') as dueondt from `fees_studentdetail` where fstid='".$slist['id']."'"; 
	  $installment=$db->runQuery("$qry");
	  
$string .= '<td class="col-4" style="width:300px;">

	  <table width="100%" border="0" cellspacing="0" cellpadding="0">';
		   $i=1;
		  	foreach($installment as $inst){
		  
		  $string .= '<tr>
			<td>'.$inst['inst'].'</td>
			<td>'.$inst['dueondt'].'</td>
		  </tr>';
		  
		   $i++; }
		  
		$string .= '</table>
	  </td>

	  

    </tr>';

	$i++; } 

	$k = 0;

	foreach($mySession->StudentInst as $slist) {

		$m=$i%2; 

		if($m==0)

		{

			$class="tr-even";	

		}else{

			$class="tr-odd";	

		}

	

   $string .= '<tr class="'.$class.'" id="class-timing-1">

      <td class="col-1"><input type="checkbox" name="chk[]" value="s_'.$k.'" /></td>

	  <td class="col-2">'.$slist['catname'].'</td>

      <td class="col-3">'.$slist['noofinst'].'</td>

     

      <td class="col-4" style="width:100px;">

	  <table width="100%" border="0" cellspacing="0" cellpadding="0">';

		  $t=1;
		  foreach($slist['inst'] as $inst){
		  
		  $string .= '<tr>
			<td>'.$inst['inst'].'</td>
			<td>'.$inst['dueon'].'</td>
		  </tr>';
		  
		    $t++; }		   
		  
		$string .= '</table>
	  </td>
    </tr>';
	$i++; $k++; }
$string .= '</tbody>';
$string = jschars($string);

?>
jQuery("#page-yield #class-timings-list").html("<?=$string?>");
Modalbox.hide();

<? } ?>