<? global $mySession; ?>
<link href="<?=CSS_URL?>student/guardians.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1>Parents info</h1>
  <h3>Parents profile</h3>
  <div id="app-back-button">
      <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="inner-tab-menu">
  <ul>
    <li style="width:120px;"><a href="<?=BASE_PATH?>student/profile/studentid/<?=$this->studentdetail['id']?>">Student profile</a></li>
    
     <?php /*?> <li><a href="<?=BASE_PATH?>student/addguardian/studentid/<?=$this->studentdetail['id']?>">Add guardian</a></li><?php */?>
    
  </ul>
</div>

<div id="page-yield">

  

  <div id="student_profile_heading">



    <div id="student_main_info">
      <span class="name"> <? echo $this->studentdetail['stname']; ?>  </span>
      <span class="course"> <?=LNG_GRADE?> <?=$this->studentdetail['grade_name']?>; <?=LNG_BATCH?>: <?=$this->studentdetail['batchname']?> </span>&nbsp;
      <span class="adm"> <?=LNG_ADM_NO?> : <? echo $this->studentdetail['admission_no'];?> </span>
    </div>

    <div class="extender"> </div>

  </div>

  <div id="guardians-links" style="text-align:left">

    <ul>
      <span><?=LNG_PARENTS_GUARDIANS?></span>
     <?php /*?> <? 
	  foreach($this->studentdetail as $studentdetail){ 
	  ?>
        <li><a href="#guardian-details-id-1"><? echo $this->studentdetail['Gaurdian']; ?> </a> (<? echo $this->studentdetail['relation']; ?>)</li>
      <? } ?>
   <?php */?>
 </ul>
  </div>


  <div id="parent-list">

    

      <a name="guardian-details-id-1"> </a>
      <div id="new_profile_info_top" style="text-align:left;">
        <div class="profile_top_banner"><img alt="Topbanner" src="<?=IMAGES_URL?>master_student/profile/topbanner.png?<?=UPDATE_KEY?>"></div>
        
		<div class="profile_info_label"> <?=LNG_NAME?> </div>
        <div class="profile_info_text">
         <? echo $this->studentdetail['Gaurdian']; ?>
        </div>

        <div class="profile_info_label2"><?=LNG_RELATION?></div>
        <div class="profile_info_text2"><? echo $this->studentdetail['relation']; ?></div>
		
		 <div class="profile_info_label"><?=LNG_USERNAME?></div>
        <div class="profile_info_text"><? echo $this->studentdetail['username']; ?></div>
		

        <?php /*?><div class="profile_info_label">Date of birth</div>
        <div class="profile_info_text"><? echo $this->studentdetail['dob_dt']; ?></div>


        <div class="new_profile_info_area1">
          <div class="profile_info_label2">Email</div>
          <div class="profile_info_text2"><? echo $this->studentdetail['email']; ?></div>

          <div class="profile_info_label">Phone 1</div>
          <div class="profile_info_text"><? echo $this->studentdetail['office_phone1']; ?></div>
        </div>

        <div class="new_profile_info_area1">
          <div class="profile_info_label2">Phone 2</div>
          <div class="profile_info_text2"><? echo $this->studentdetail['office_phone2']; ?></div>

          <div class="profile_info_label">Mobile phone</div>
          <div class="profile_info_text"><? echo $this->studentdetail['mobile_phone']; ?></div>
        </div>

        <div class="new_profile_info_area1">
          <div class="profile_info_label2">Address</div>
          <div class="profile_info_text2"><? echo $this->studentdetail['office_address_line1']; ?></div>

          <div class="profile_info_label"> </div>
          <div class="profile_info_text"><? echo $this->studentdetail['city'].' '.$this->studentdetail['state']; ?></div>
        </div>

        <div class="new_profile_info_area1">
          <div class="profile_info_label2">Income</div>
          <div class="profile_info_text2"><? echo $this->studentdetail['income']; ?></div>

          <div class="profile_info_label">Occupation</div>
          <div class="profile_info_text"><? echo $this->studentdetail['occupation']; ?></div>
        </div>
        <div class="extender"></div>
      </div><?php */?>
      <div class="button-pair">
        <? if($mySession->user['usertype']=='S') { ?>
        <div class="parent-edit-button">
          <a href="<?=BASE_PATH?>student/editguardian/studentid/<? echo $this->studentdetail['id']; ?>"><?=LNG_EDIT?></a>
        </div>
        <? } ?>
      </div>

      <div class="extender"></div>
    

  </div>
</div> </div></div>

      <div class="extender"></div>
    