<?
$db = new Db();
?>
<link href="<?=CSS_URL?>student/guardians.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
<div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_NOTES?></h1>
  <h3><?=LNG_NOTES_ABOUT_STUDENT?></h3>
  <div id="app-back-button">
      <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="inner-tab-menu">
  <ul>
    <li style="width:120px;"><a href="<?=BASE_PATH?>student/profile/studentid/<?=$this->studentdetail['id']?>"><?=LNG_STUDENT_PROFILE?></a></li>
    
     <?php /*?> <li><a href="<?=BASE_PATH?>student/addguardian/studentid/<?=$this->studentdetail['id']?>">Add guardian</a></li><?php */?>
    
  </ul>
</div>

<div id="page-yield">

  

  <div id="student_profile_heading">
    <div id="student_main_info">
      <span class="name"> <? echo $this->studentdetail['stname']; ?>  </span>
      <span class="course"> <?=LNG_GRADE?> <?=$this->studentdetail['grade_name']?>; <?=LNG_BATCH?>: <?=$this->studentdetail['batchname']?> </span>&nbsp;
      <span class="adm"> <?=LNG_ADM_NO?> : <? echo $this->studentdetail['admission_no'];?> </span>
    </div>

    <div class="extender"> </div>

  </div>	
	
	
	 <? foreach($this->noteslist as $noteslist){ 
	 $username = $noteslist['username'];
	if($noteslist['usertype']=='T') {
	 	$qry = "select concat(first_name,' ',last_name) as username from employees where userid='".$noteslist['write_by']."'";
		$getusername = $db->runQuery($qry);
		$username = $getusername[0]['username'];
	 }
	 
	 ?>
		<div id="reminder-message1" style="border-bottom:1px dashed #CCCCCC; margin-bottom:5px; text-align:left;">
			<div style="font-size:14px; color:#838383;"> 
				<strong><?=$username?></strong> <span style="font-size:12px">said on <?=$comments['dt']?>
			</span></div>
			<div style="font-size:13px; color:#909090;"> <?=$noteslist['note']?></div>				 
			
				<br />
		</div>
	<? } ?>	


</div></div>

      <div class="extender"></div>
    