<link href="<?=CSS_URL?>student/reports.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_STUDENTS?></h1>
  <h3><?=LNG_REPORTS_CENTER?></h3>
  <div id="app-back-button">
     <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>


<div id="page-yield">

  <div id="exam-results-dashboard" style="text-align:left;">

    <h3><?=LNG_ACADEMICS?></h3>

    <div class="exam-results-reports-col">
      
      <h4><?=LNG_RECENT_EXAMS?></h4>
	  
      <ul>
      	<? 
		foreach($this->recentexam as $recentexam) { ?>  
          <li><a href="<?=BASE_PATH?>exam/generatedreport?exam_group_id=<?=$recentexam['id']?>&amp;student=<?=$this->studentid?>"><?=$recentexam['name']?></a></li>
       <? }
	   ?>
          
        
      </ul>
    

      <h4><?=LNG_SUBJECTWISE_RESULTS?></h4>
      <ul>
        <? 
		foreach($this->examsubject as $examsubject) { ?>  
          <li><a href="<?=BASE_PATH?>exam/generatedreport3?student_id=<?=$this->studentid?>&subject_id=<?=$examsubject['id']?>"><?=$examsubject['name']?></a></li>
        <? } ?>
        
        
      </ul>
    </div>
    
    <div class="exam-results-reports-col">

      <h4><?=LNG_DETAILED_REPORTS?></h4>
      <ul>
        
        <li><a href="<?=BASE_PATH?>exam/generatedreport4?student=<?=$this->studentid?>&amp;type=grouped"><?=LNG_FINAL_REPORT_EXAM_GROUPED?></a></li>
        <?php /*?><li><a href="<?=BASE_PATH?>exam/previousyearsmarksoverview?student=1&amp;type=grouped"><?=LNG_COMPARE_WITH_PAST_YEARS?>
		</a>
		</li><?php */?>
        
      </ul>

      


    </div>

    <div class="extender"> </div>

  </div>

  <div id="attendance-reports-dashboard" style="text-align:left;">

    <h3><?=LNG_ATTENDANCE?></h3>

    <h4><?=LNG_DETAILED_REPORTS?></h4>

    <ul>
      <li><a href="<?=BASE_PATH?>attendancereport/studentdetails/profileid/<?=$this->studentid?>"><?=LNG_CURRENT_YEAR_REPORTS?></a></li>
    </ul>
      
  </div>

</div> </div>

      <div class="extender"></div>
    