<link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
<?
global $mySession;
if($mySession->setlanguage!=2) {
	$ln_default_left = 'left';
	$ln_default_right = 'right';
} else {
	$ln_default_left = 'right';
	$ln_default_right = 'left';
}
?>
<script type="text/javascript">
function form_vail()
{
 	if(document.getElementById("search_keyword").value==""){
	alert("Please Enter ID or Passport")
	document.getElementById("search_keyword").focus();
	return false;
	}
	
	getajax('<?=BASE_PATH?>student/liststudentsofother/','search_keyword='+document.getElementById("search_keyword").value,'students');
	
return false;

}
</script>

      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_SEARCH_FROM_OTHER?></h1>
  <h3><?=LNG_SEARCH_OTHER_STUDENT?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">
<form action="" class="new_subject" id="new_subject" method="post" onsubmit="return form_vail()">
 
  
  <div style="float:<?=$ln_default_left?>; width:780px; margin-<?=$ln_default_left?>:5px; ">
  <div class="label-field-pair-select-class" style="height:40px; width:750px">
  <label for="student-detail-select-class" style="width:100px"><?=LNG_KEYWORD?></label>
    <div class="label-field-pair text-input-bg" style="width:150px;">
	<input type="text" name="search_keyword" id="search_keyword" value="">
	
	</div>
	<label for="student-detail-select-class">&nbsp;</label>
   
	<div class="submit-button" style="float:left; width:300px">
      <input type="submit" class="submit-button" name="commit" value="<?=LNG_FILTER?>">
	  <span class="cls_hide" id="export_span">
	  	<input type="button" class="submit-button" name="commit" onclick="this.form.action='<?=BASE_PATH?>student/askforstudent/'; this.form.submit()" value="<?=LNG_REQUEST_FOR_MORE_INFO?>" />
		</span>
    </div>
	<div class="extender"></div>
	</div>
<div class="extender"></div>
  <div id="students"> </div>
  </div>
  <div class="extender"></div>
</form>
</div> </div>

      <div class="extender"></div>
