<?
global $mySession;
$db = new Db();

//echo"<pre>";print_r($this->request);exit;
?>
<link href="<?=CSS_URL?>student/guardians.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_STUDENT_INFO?></h1>
  <h3><?=LNG_STUDENT_INFORMATION?></h3>
  <div id="app-back-button">
      <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">
<?
//	if(isset($this->request['sec_id'])){
?>
	<div id="box">
		<div id="stu_req"> <?=LNG_RECIEVED_FROM?></div>
	  <?
	  tframe_pre();
	  ?>
	  <table id="listing" align="center" cellpadding="1" cellspacing="1" width="100%">
      	<tr class="tr-head">
        <td>
          <?=LNG_FROM?>
        </td>
		 <td>
          <?=LNG_STUDENT?>
        </td>
        <td>
          <?=LNG_MESSAGE?>
        </td>
		<td>
          <?=LNG_ACTION?>
        </td>
      </tr>
      <tr><td></td></tr>
	  <? if(isset($this->request) && count($this->request) > 0) { ?>
	  <? $i=1; 
	  foreach($this->request as $strequest) {
	   $m=$i%2; 
			if($m==0)
			{
				$class="tr-odd";	
			}else{
				$class="tr-even";	
			}
			//echo"<pre>";print_r($this->request);
	   ?>
		  <tr class="<? echo $class; ?>">
			<td class="col-3"><?=$strequest['sc_name']?></td>
			<td class="col-3"><?=$strequest['stname']?></td>
			<td class="col-4"><?=$strequest['message']?></td>
			<td class="col-3">
				<small>
					<?
					if($strequest['act_status']==0){
					?>
						<a href="<?=BASE_PATH?>student/changestatus/requestid/<?=$strequest['id']?>/status/accept"><?=LNG_ACCEPT?></a>&nbsp;|&nbsp;
						<a href="<?=BASE_PATH?>student/changestatus/requestid/<?=$strequest['id']?>/status/decline"><?=LNG_DECLINE?></a>&nbsp;|&nbsp;
						<a href="<?=BASE_PATH?>student/deletereq/requestid/<?=$strequest['id']?>"><?=LNG_DELETE?></a>
					<?
						} elseif ($strequest['act_status']==1) {
							?>
							<?=LNG_REQUEST_DECLINED?>&nbsp;|&nbsp;
							<a href="<?=BASE_PATH?>student/deletereq/requestid/<?=$strequest['id']?>"><?=LNG_DELETE?></a>
							<?
						} else {
							?>
							<?=LNG_REQUEST_ACCEPTED?>&nbsp;|&nbsp;
							<a href="<?=BASE_PATH?>student/deletereq/requestid/<?=$strequest['id']?>"><?=LNG_DELETE?></a>
							<?
						}
					?>
					
				</small>
			</td>
		  </tr>
		 <? $i++; } ?>
	<? } ?>
	  </table>
	  <?
	  tframe_post();
	  ?>
	  
	  <div id="stu_req" style="padding-top:20px;"> <?=LNG_SENT_TO?></div>
	  <?
	  tframe_pre();
	  ?>
	  <table id="listing" align="center" cellpadding="1" cellspacing="1" width="100%">
      	<tr class="tr-head">
        <td>
          <?=LNG_SENTTO?>
        </td>
		 <td>
          <?=LNG_STUDENT?>
        </td>
        <td>
          <?=LNG_MESSAGE?>
        </td>
		<td>
          <?=LNG_STATUS?>
        </td>
      </tr>
      <tr><td></td></tr>
	  <? if(isset($this->sentrequest) && count($this->sentrequest) > 0) { ?>
	  <? $i=1; 
	  foreach($this->sentrequest as $srequest) {
	   $m=$i%2; 
			if($m==0)
			{
				$class="tr-odd";	
			}else{
				$class="tr-even";	
			}
			//echo"<pre>";print_r($this->srequest);
	   ?>
		  <tr class="<? echo $class; ?>">
			<td class="col-3"><?=$srequest['sc_name']?></td>
			<td class="col-3"><?=$srequest['stname']?></td>
			<td class="col-4"><?=$srequest['message']?></td>
			<td class="col-3">
				<small>
					<?
					if($srequest['act_status']==0){
					?>
						<?=LNG_IN_PROCESS?>
					<?
						} elseif ($srequest['act_status']==1) {
							?>
							<?=LNG_DECLINED?>&nbsp;|&nbsp;
							<a href="<?=BASE_PATH?>student/deletereq/requestid/<?=$strequest['id']?>"><?=LNG_DELETE?></a>
							<?
						} else {
							?>
							<a href="<?=BASE_PATH?>student/requestedstudent/studentid/<?=$srequest['studentid']?>"><?=LNG_ACCEPTED?></a>&nbsp;|&nbsp;
							<a href="<?=BASE_PATH?>student/deletereq/requestid/<?=$strequest['id']?>"><?=LNG_DELETE?></a>
							<?
						}
					?>
					
				</small>
			</td>
		  </tr>
		 <? $i++; } ?>
	<? } ?>
	  </table>
	  	  <?
	  tframe_post();
	  ?>

	</div>
<?
//	}
?>
</div></div>

      <div class="extender"></div>
    