<link href="<?=CSS_URL?>finance/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
<? global $mySession;
   $db=new Db(); ?> 
 <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>admission/admission_page_logo.jpg">
  <h1>Admission</h1>
  <h3>Fees Details</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">
  <div class="add_sub">
   <a href="#" onclick="getajax('<?=BASE_PATH?>student/feescreate/batchid/<?=$this->batchid?>','','modal-box',1)">Add fees</a>
  </div>
  <form action="<?=$this->url(array('controller'=>'student','action'=>'submitfees'),null,true);?>" method="post"><div style="margin:0;padding:0;display:inline"><input name="studentid" value="<?=$this->studentid?>" type="hidden"></div>
	<table width="100%" id="class-timings-list">
  <tbody><tr class="tr-head">
    <td>#</td>
	<td>Name</td>
    <td>No. of Installments</td>
    <td>Installment Amount</td>
	
  </tr>
  	<? 
		$i=1;
	foreach($this->slist as $slist) {
		$m=$i%2; 
		if($m==0)
		{
			$class="tr-even";	
		}else{
			$class="tr-odd";	
		}
	 ?>
   <tr class="<? echo $class; ?>" id="class-timing-1">
      <td class="col-1"><input type="checkbox"  name="chk[]" value="b_<?=$slist['id']?>" /></td>
	  <td class="col-2"><?=$slist['catname']?></td>
      <td class="col-3"><?=$slist['noofinst']?></td>
      <? 
	  
	  $qry="select *, DATE_FORMAT(dueon, '%M %d, %Y') as dueondt from `fees_structuredetail` where fsid='".$slist['id']."'"; 
	  $installment=$db->runQuery("$qry");
	  ?>
      <td class="col-4" style="width:100px;">
	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <? $t=1;
		  	foreach($installment as $inst){
		  ?>
		  <tr>
			<td><?=$inst['inst']?></td>
			<td><?=$inst['dueondt']?></td>
		  </tr>
		  <?
		   $t++; }
		   
		  ?>
		</table>

	  </td>
	  
    </tr>
	<? $i++; } 
	$k = 0;
	foreach($mySession->StudentInst as $slist) {
		$m=$i%2; 
		if($m==0)
		{
			$class="tr-even";	
		}else{
			$class="tr-odd";	
		}
	 ?>
   <tr class="<? echo $class; ?>" id="class-timing-1">
      <td class="col-1"><input type="checkbox" name="chk[]" value="s_<?=$k?>" /></td>
	  <td class="col-2"><?=$slist['catname']?></td>
      <td class="col-3"><?=$slist['noofinst']?></td>
     
      <td class="col-4" style="width:100px;">
	  <table width="100%" border="0" cellspacing="0" cellpadding="0">
		  <? $t=1;
		  	foreach($slist['inst'] as $inst){
		  ?>
		  <tr>
			<td><?=$inst['inst']?></td>
			<td><?=$inst['dueon']?></td>
		  </tr>
		  <?
		    $t++; }		   
		  ?>
		</table>

	  </td>
	  
    </tr>
	<? $i++; $k++; }?>
	</tbody></table>
	<?
	//echo "<pre>";
	//print_r($mySession->StudentInst);
	?>
	<div class="save-proceed-button" style="width:550px;text-align:left;">
      <div style="width:180px; float:right;text-align:left;"><input name="commit" value="Finish" type="submit"></div>
     
      </div>
    </form>
  </div>
 </div>
<div id="modal-box" style="display: none;"></div>

      <div class="extender"></div>