<link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>student_details/student_details_logo.png">
  <h1><?=LNG_STUDENT_DETAILS?></h1>
  <h3><?=LNG_VIEW_DETAILS?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li style="width:125px;"><a href="<?=BASE_PATH?>student/advancedsearch"><?=LNG_ADVANCE_SEARCH?></a></li>
  </ul>
</div>
<div id="page-yield">
<form action="" class="new_subject" id="new_subject" method="post" onsubmit="getajax('<?=BASE_PATH?>student/liststudentsbyclass/','?'+Form.serialize(this),'students'); return false">
  <div class="label-field-pair-select-class">
    <label for="student-detail-select-class"><?=LNG_SELECT_A_GRADE?></label>
    <div class="text-input-bg">
	<select onchange="getajax('<?=BASE_PATH?>student/batchlistcombo/','?gradeid='+this.value+'&search_year='+document.getElementById('search_year').value,'batchlist');" name="search_gradeid" id="search_gradeid">
	<option value=""><?=LNG_SELECT_A_GRADE?></option>
	<? if(isset($this->batchlist) && count($this->batchlist) > 0) { ?>
		<? foreach($this->batchlist as $batchlist) { ?>
			<option value="<?=$batchlist['id']?>"><?=$batchlist['grade_name']?></option>
		<? } ?>
	<? } ?>
	</select></div>
    
	
	 <label for="student-detail-select-class"><?=LNG_SESSION_START_YEAR?></label>
    <div class="text-input-bg">
	<select name="search_year" id="search_year" onchange="if(document.getElementById('search_gradeid').value!='') { getajax('<?=BASE_PATH?>student/batchlistcombo/','?gradeid='+document.getElementById('search_gradeid').value+'&search_year='+this.value,'batchlist'); }">
	<? 
	$yy = date("Y");
	for($i=$yy; $i > ($yy-2); $i--){ ?>
	<option value="<?=$i?>"><?=$i?></option>
	<? } ?>
	
	</select></div>
	<div class="extender"></div>
	<label for="student-detail-select-class"><?=LNG_SELECT_A_BATCH?></label>
    <div class="text-input-bg" id="batchlist">
	<select name="search_batchid" id="search_batchid">
	<option value=""><?=LNG_SELECT_A_BATCH?></option>
	
	</select></div>
	
	<label for="student-detail-select-class"><?=LNG_SELECT_A_RELIGION?></label>
    <div class="text-input-bg">
	<select name="search_religion" id="search_religion">
	<option value=""><?=LNG_SELECT_A_RELIGION?></option>
	<option value="1">Islam</option>
	<option value="2">Hindu</option>
	
	</select></div>
	<div class="extender"></div>
	<label for="student-detail-select-class"><?=LNG_KEYWORD?></label>
    <div class="label-field-pair text-input-bg" style="width:250px;">
	<input type="text" name="search_keyword" id="search_keyword" value="">
	
	</div>
	<label for="student-detail-select-class">&nbsp;</label>
   
	<div class="submit-button" style="float:left; width:220px">
      <input type="submit" class="submit-button" name="commit" value="<?=LNG_FILTER?>">
	  <input type="button" class="submit-button" name="commit" onclick="this.form.action='<?=BASE_PATH?>student/exportxls/'; this.form.submit()" value="<?=LNG_EXPORT?>">
    </div>
	
  </div>
<div class="extender"></div>
  <div id="students"> </div>
</form>
</div> </div>

      <div class="extender"></div>
