<div id="content_wrapper">
      <div id="side_bar">
        <div id="sidebar_news_area">
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="Exam" src="<?=IMAGES_URL?>examination/show_exam.png">
  <h1>Exams</h1>
  <h3>Create Exam</h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="page-yield">
    
<div class="box">
     <div class="label-field-pair">
   <label for="student_class">Select a class:
<img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
   </label>
   <div class="text-input-bg">
  <select onchange="Element.show('loader'); new Ajax.Request('/exam/update_batch', {asynchronous:true, evalScripts:true, onSuccess:function(request){Element.hide('loader')}, parameters:'class_name='+ value + '&amp;authenticity_token=' + encodeURIComponent('BwVDJkXp81PzRlHDNPgqE8xs3LgnL4IH+G5vEg+zGBk=')})" name="classes[name]" id="classes_name"><option value="">Select a class</option>
<option value="1">BCA</option></select>
</div></div>

<div style="float: left; width: 800px;" id="update_batch"></div>
<div class="extender"></div>
 </div></div> </div>

      <div class="extender"></div>
    </div>