<div id="content_wrapper">
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>show_timetable.png">
  <h1><?=LNG_TIMETABLE?></h1>
  <h3><?=LNG_HOME?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

  

  <div class="box2">
    
      <div class="link-box">
        
        
          <div class="link-heading"><a href="<?=BASE_PATH?>timetable/selectclass2"><?=LNG_CREATE_EDIT_TIMETABLE?></a></div>
        
        <div class="link-descr"><?=LNG_TIMETABLE_TEXT2?></div>
      </div>

      <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>classtimings"><?=LNG_SET_CLASS_TIMINGS?></a></div>
        <div class="link-descr"><?=LNG_TIMETABLE_TEXT3?></div>
      </div>
	  
      <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>timetable/view"><?=LNG_VIEW_TIMETABLE?></a></div>
        <div class="link-descr"><?=LNG_TIMETABLE_TEXT4?></div>
      </div>
	  
    <?php /*?><div class="link-box">
      <div class="link-heading"><a href="<?=BASE_PATH?>timetable/timetable">Institutional Timetable</a></div>
      <div class="link-descr">View the entire timetable for a day</div>
    </div><?php */?>
    
      <div class="link-box">
        <div class="link-heading"><a href="<?=BASE_PATH?>weekday"><?=LNG_CREATE_WEEKDAYS?></a></div>
        <div class="link-descr"><?=LNG_CREATE_WEEKDAYS?></div>
      </div>
    
    <div class="extender"></div>
  </div>
</div> </div>

      <div class="extender"></div>
    </div>