
<div id="content_wrapper">
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>show_timetable.png">
  <h1><?=LNG_TIMETABLE?></h1>
  <h3><?=LNG_SELECT_CLASS_TO_EDIT?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#">
		<img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back">
	</a>
  </div>
</div>

<div id="page-yield">
  
  

    <div class="label-field-pair">
      <label for="timetable_entry_class_id"><?=LNG_SELECT_A_BATCH?></label>
      <div class="text-input-bg"> <select name="batch_id" id="timetable_entry_batch_id" onchange="getajax('<?=BASE_PATH?>timetable/edit2','?batch_id='+this.value,'timetableview');"><option value=""><?=LNG_SELECT_A_BATCH?></option>
		<?
		foreach($this->cblist as $cblist) {  ?>
		<option value="<?=$cblist['id']?>"><?=$cblist['grade_name']?> - <?=$cblist['name']?></option>
		<? } ?>
		</select>
      </div>
    </div>
	<div id="timetableview"></div>
</div> </div>

      <div class="extender"></div>
    </div>