<?
	global $mySession;	
?>

<link href="<?=CSS_URL?>timetable/view.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
<div id="content"> 
	<div id="content-header">
	  <img src="<?=IMAGES_URL?>show_timetable.png">
	  <h1><?=LNG_TIMETABLE?></h1>
	  <h3><?=LNG_VIEW_BATCH_TIMETABLE?></h3>
	  
		<div id="app-back-button">
		<a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
	  </div>
	  
	</div>

<div id="page-yield">

  

	 <? if(count($mySession->user['userstudentid']) > 1) {		
		?>
			<form method="post" action="<?=BASE_PATH?>timetable/studentview"><div style="margin: 0pt; padding: 0pt; display: inline;"><input type="hidden" value="BwVDJkXp81PzRlHDNPgqE8xs3LgnL4IH+G5vEg+zGBk=" name="authenticity_token"></div>
				<div class="label-field-pair">
				  <label for="timetable_entry_class_id" style="width:130px; margin-right:30px;"><?=LNG_DETAILED_REPORT_FOR?></label>
				   <img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
				  <div class="text-input-bg">
				  <select onchange="getajax('<?=BASE_PATH?>timetable/updatetimetableview','?batch_id='+this.value,'timetable_view');" name="timetable_entry[grade_id]" id="timetable_entry_class_id">					
					<? foreach($this->studentlist as $studentlist) { ?>
						<option value="<?=$studentlist['batchid']?>"<? if(@$studentlist['id']==$this->studentid) { ?> selected="selected"<? } ?>>
							<?=$studentlist['first_name']?> <?=$studentlist['middle_name']?> - <?=$studentlist['batchname']?>
						</option>
					<? } ?>
				
				</select>
				  </div>
				</div>
			  </form>
			  <div class="extender"> </div>
		
		<? 		
	}else{ ?>
	 <div class="label-field-pair">
		<label style="width:3000px;"> <?=LNG_DETAILED_REPORT_FOR?> <?=$this->studentdetail['stname']?> (<?=LNG_BATCH?> <?=$this->studentdetail['batchname']?>)</label>
	  </div>
    <div class="extender"> </div>  
    <? } ?>


  <div id="timetable_view"> </div>
</div> </div>

      <div class="extender"></div>

<script>
	getajax('<?=BASE_PATH?>timetable/updatetimetableview','?batch_id=<?=$this->studentdetail['batchid']?>','timetable_view');
</script>
