
	<? foreach($this->employee as $employee) { ?>
		 <div style="position: relative;<? if(@$this->colorcode[0]['colorcode']!='' and @$this->colorcode[0]['colorcode']!='#ffffff') { ?> background-color:<?=$this->colorcode[0]['colorcode']?>;<? } ?>" class="employees_subject" id="emp_sub_<?=$employee['emp_sub_id']?>"> <?=$employee['first_name']?> </div>
		 <script type="text/javascript">
		//<![CDATA[
		new Draggable("emp_sub_<?=$employee['emp_sub_id']?>", {revert:true})
		//]]>
		</script>
	<? } ?>
	<div class="extender"></div>
	<div style="font-size:11px; font-weight:bold; padding-left:25px; color:#990033"><< Drag & Drop</div>
