
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>show_settings.png" alt="">
  <h1><?=LNG_BATCH?></h1>
  <h3>Assign Tutor</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>

<div id="page-yield">

  <ul id="tutor-list">
    

  </ul>

  <div class="label-field-pair">
    <label for="department_name">Department</label>
    <div class="text-input-bg"><select id="subject_assignment_department_id" name="subject_assignment[department_id]" onchange="new Ajax.Request('<?=BASE_PATH?>batches/update_employees', {asynchronous:true, evalScripts:true, parameters:'department_id='+value+'&amp;batch_id=1&amp;'+ + '&amp;authenticity_token=' + encodeURIComponent('K3shzZH6++B7hEMkGYpq5KHrQxkUAUZY4LCxTTPsXvM=')})"><option value="">Select department</option>
<option value="1">Fedena Admin</option></select>
    </div>
  </div>
  <div id="employee-list"></div>
  <div class="extender"></div>

</div> </div>

      <div class="extender"></div>
    