
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="Exam" src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_EDIT_BATCHES?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>


<div id="page-yield">

  

  <div class="box" style="text-align:left;">
    <div class="bread_crumb">
      <a href="<?=BASE_PATH?>grades"><?=LNG_GRADES?></a> &raquo;
      <a href="<?=BASE_PATH?>grades/show/gradeid/<?=$this->batchdetail['grade_id']?>"><?=$this->batchdetail['grade_name']?></a> &raquo; <?=LNG_BATCH?> &raquo; 
      <a href="<?=BASE_PATH?>batches/show/gradeid/<?=$this->gradeid?>/batchid/<?=$this->batchid?>"> <?=$this->batchdetail['name']?></a> &raquo;
      <?=LNG_EDIT?>
    </div>


    <form method="post" id="edit_batch_1" class="edit_batch" action="<?=BASE_PATH?>batches/edit/gradeid/<?=$this->gradeid?>/batchid/<?=$this->batchid?>"><div style="margin:0;padding:0;display:inline"><input type="hidden" value="put" name="_method"></div>

      <div class="label-field-pair">
        <div class="label-container"><label for="batch_name"><?=LNG_NAME?></label></div>
        <div class="input-container"><?php echo $this->form->batch_name?></div>
      </div>
       <div class="label-field-pair">
        <div class="label-container"><label for="batch_name">Class Teacher</label></div>
        <div class="text-input-bg">
		<?php echo $this->form->batches_employee_id?></div>
      </div>
	  
        <div class="label-field-pair">
        <div class="label-container"><label for="batch_start_date"><?=LNG_START_DATE?></label></div>
        <div class="input-container"><?php echo $this->form->batch_startdate?> <img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $(this).previous(), {year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
      </div>
	  
	  <div class="label-field-pair">
        <div class="label-container"><label for="batch_start_date"><?=LNG_SECONT_SEM_START_DATE?></label></div>
        <div class="input-container"><?php echo $this->form->batch_second_sem_start?> <img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $(this).previous(), {year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
      </div>

      <div class="label-field-pair">
        <div class="label-container"><label for="batch_end_date"><?=LNG_END_DATE?></label></div>
        <div class="input-container"><?php echo $this->form->batch_enddate?> <img style="border:0px; cursor:pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $(this).previous(), {year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
      </div>

      <input type="submit" value="<?=LNG_SAVE?>" name="commit" class="submit_button">


    </form>

    <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
