<link href="<?=CSS_URL?>batches/new.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>show_settings.png" alt="Exam">
  <h1>Grades</h1>
  <h3><?=LNG_NEW_BATCH?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>


<div id="page-yield">

  

  <div style="text-align:left;"> 
    <div class="bread_crumb">
      <a href="<?=BASE_PATH?>grades">Grades</a> &raquo;
      <?=$this->classdetail[0]['grade_name'];?> &raquo;
      <?=LNG_NEW_BATCH?>
    </div>

    <form style="text-align:left;" action="<?=BASE_PATH?>batches/new/gradeid/<?=$this->classdetail[0]['id']?>" class="new_batch" id="new_batch" method="post">
	<div id="necessary-field-notification"> <?=LNG_FIELDS_MARKED_WITH?> <span class="necessary-field">*</span> <?=LNG_MUST_BE_FILLED?></div>
	<div style="margin:0;padding:0;display:inline">
	<input name="authenticity_token" value="y+QApAfdoJNc/WoznkxrUJos4+Vkz+nw80Mz/W9KRyk=" type="hidden">
	</div>
      
      <div class="label-field-pair">
        <div class="label-container"><label for="batch_name"><?=LNG_NAME?> <span class="necessary-field">*</span></label></div>
        <div class="input-container">
		<?php echo $this->form->batch_name?></div>
      </div>
	  <div class="label-field-pair">
        <div class="label-container"><label for="batch_name"><?=LNG_BATCH_TEACHER?></label></div>
        <div class="text-input-bg">
		<?php echo $this->form->batches_employee_id?></div>
      </div>

      <div class="label-field-pair">
        <div class="label-container"><label for="batch_start_date"><?=LNG_START_DATE?> <span class="necessary-field">*</span></label></div>
        <div class="input-container">
		<div style="float:left"><?php echo $this->form->batch_startdate?></div><div style="float:left; padding-left:5px; padding-top:10px">
		 <img alt="Calendar" class="calendar_date_select_popup_icon" onclick="new CalendarDateSelect( $('batch_startdate'), {year_range:10} );" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" style="border:0px; cursor:pointer;"></div></div>
      </div>
	  
	  <div class="label-field-pair">
        <div class="label-container"><label for="batch_start_date"><?=LNG_SECONT_SEM_START_DATE?> <span class="necessary-field">*</span></label></div>
        <div class="input-container">
		<div style="float:left"><?php echo $this->form->batch_second_sem_start?></div><div style="float:left; padding-left:5px; padding-top:10px">
		 <img alt="Calendar" class="calendar_date_select_popup_icon" onclick="new CalendarDateSelect( $('batch_second_sem_start'), {year_range:10} );" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" style="border:0px; cursor:pointer;"></div></div>
      </div>

      <div class="label-field-pair">
        <div class="label-container"><label for="batch_end_date"><?=LNG_END_DATE?> <span class="necessary-field">*</span></label></div>
        <div class="input-container">
		<div style="float:left"><?php echo $this->form->batch_enddate?></div><div style="float:left; padding-left:5px; padding-top:10px">
		 <img alt="Calendar" class="calendar_date_select_popup_icon" onclick="new CalendarDateSelect( $('batch_enddate'), {year_range:10} );" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" style="border:0px; cursor:pointer;"></div></div>
      </div>

      <?php /*?><div class="label-field-pair">
        <div class="label-container"><label>Import previous batch Subjects</label></div>
        <div class="input-container"><input id="import_subjects" name="import_subjects" value="0" type="checkbox"></div>
      </div><?php */?>

      <?php /*?><div class="label-field-pair">
        <div class="label-container"><label>Import previous batch Master fees</label></div>
        <div class="input-container"><input id="import_fees" name="import_fees" value="0" type="checkbox"></div>
      </div><?php */?>

      <input class="submit_button" name="commit" value="<?=LNG_SAVE?>" type="submit">

    </form>

    <div class="extender"></div>

  </div></div>
 </div>

      <div class="extender"></div>
    