<?
if($this->mode==0) {
$string = "<div id=\"grading-levels-form\">
  <h4>".LNG_GRADE." ".$this->detail['grade_name']."</h4>
  <form action=\"\" class=\"new_subject\" id=\"new_subject\" method=\"post\" onsubmit=\"getajax('".BASE_PATH."subjectstemplate/editsubject/mode/update/','?'+Form.serialize(this),'modal-box',2)\">
   <input id=\"subjectid\" name=\"subjectid\" type=\"hidden\" value=\"".$this->subjectid."\" />
    <input id=\"batchid\" name=\"gradeid\" type=\"hidden\" value=\"".$this->gradeid."\" />
    <input id=\"subject_elective_group_id\" name=\"elective_group_id\" type=\"hidden\" />
    <div id=\"form-errors\"></div>
    <div class=\"label-field-pair\">
      <div class=\"label-container\">
        <label for=\"subject_name\">".LNG_NAME."</label>
      </div>
      <div class=\"input-container\">
        <input id=\"subject_name\" name=\"name\" size=\"30\" value=\"".$this->sdetail['name']."\" type=\"text\" />
      </div>
    </div>
	<div class=\"label-field-pair\">
      <div class=\"label-container\">
        <label for=\"subject_code\">".LNG_CODE."</label>
      </div>
      <div class=\"input-container\">
        <input id=\"subject_code\" name=\"code\" size=\"30\" value=\"".$this->sdetail['code']."\" type=\"text\" />
      </div>
    </div>
    
    <input class=\"submit_button\" id=\"subject_submit\" name=\"commit\" type=\"submit\" value=\"Save\" />
  </form>
</div>";
/*<div class=\"label-field-pair\">
      <div class=\"label-container\">
        <label for=\"subject_max_weekly_classes\">Max weekly grades</label>
      </div>
      <div class=\"input-container\">
        <input id=\"subject_max_weekly_classes\" name=\"subject[max_weekly_classes]\" size=\"30\" type=\"text\" />
      </div>
    </div>
    <div class=\"label-field-pair\">
      <div class=\"label-container\">
        <label for=\"subject_no_exam\">No exam</label>
      </div>
      <div class=\"input-container\">
        <input name=\"subject[no_exams]\" type=\"hidden\" value=\"0\" />
        <input id=\"subject_no_exams\" name=\"subject[no_exams]\" type=\"checkbox\" value=\"1\" />
      </div>
    </div>*/
$string = jschars($string);
?>
Element.update("modal-box", "<?=$string?>");
Modalbox.show($('modal-box'), {title: 'Edit subject', width: 500});
<?
} elseif($this->mode==1) {
$string = "<div class=\"add_sub\">
    <a onclick=\"getajax('".BASE_PATH."subjectstemplate/newsubject/gradeid/".$this->gradeid."','','modal-box',2);\" href=\"#\">".LNG_ADD_SUBJECT."</a>
  </div>
  <ul id=\"category-list\">";
   
	foreach($this->slist as $slist) { 
      $string .= "<li class=\"listeven\" id=\"subject-1\">
        <div class=\"category-name\">".$slist['name']."</div>
        <div class=\"opt\">
          <div class=\"category-code\">".$slist['code']."</div>
          <div class=\"category-edit\"><a onclick=\"getajax('".BASE_PATH."subjectstemplate/editsubject/subjectid/".$slist['id']."','?gradeid=".$this->gradeid."','modal-box','2');\" href=\"#\">".LNG_EDIT."</a> </div>
          <div class=\"category-delete\">         
            
            
              <a onclick=\"if(confirm('Are you sure?')) { new getajax('".BASE_PATH."subjectstemplate/newsubject/mode/deletesubject/subjectid/".$slist['id']."', '?gradeid=".$this->gradeid."','modal-box','2'); }\" href=\"#\">".LNG_DELETE."</a>
            
          </div>
          
        </div>
      </li>";
  
	} 
  $string .= "</ul>";
  $string = jschars($string);
  ?>
  Element.update("subjects", "<?=$string?>");
  Modalbox.hide();
  <?
}
?>