      <div id="content"> 
<div id="content-header">
  <img alt="Exam" src="<?=IMAGES_URL?>examination/show_exam.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_EDIT?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

  

  <div id="box">
    <div class="bread_crumb">
      <a href="<?=BASE_PATH?>subjectstemplate/manageclass"><?=LNG_GRADES?></a> &raquo; <?=LNG_EDIT?>
    </div>

    <form method="post" id="new_class" class="new_class" action="<?=BASE_PATH?>subjectstemplate/new">
	
	  <div id="necessary-field-notification"> <?=LNG_FIELDS_MARKED_WITH?> <span class="necessary-field">*</span> <?=LNG_MUST_BE_FILLED?></div>
      <div class="label-field-pair">
        <div class="label-container"><label for="class_class_name"><?=LNG_GRADE_NAME?> <span class="necessary-field">*</span></label></div>
        <div class="input-container">
			<input type="text" value="" id="grade_name" name="grade_name">
		</div>
      </div>

     

      

      <input type="submit" value="<?=LNG_SAVE?>" name="commit" class="submit_button">

    </form>

    <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
