<link href="<?=CSS_URL?>grades/manage_class.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
    <img alt="Class" src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_MANAGE_GRADE?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>subjectstemplate/new"><?=LNG_NEWGRADES?></a> </li>

  </ul>
</div>
<div id="page-yield">
 <div class="box">
<h4 align="center"><?=LNG_GRADES?></h4>


	<? 
	if(isset($this->classeslist) && is_array($this->classeslist) && count($this->classeslist) > 0)
	{ ?>
	<ul id="category-list">
	
	<? $i=1;
	foreach($this->classeslist as $clist)
	{ 
		
	?>
      <li class="listodd">
        <div class="category-name"><a href="<?=BASE_PATH?>subjectstemplate/show/gradeid/<?=$clist['id']?>"><?=$clist['grade_name']?></a></div>
        <div class="category-edit"><a href="<?=BASE_PATH?>subjectstemplate/edit/gradeid/<?=$clist['id']?>"><?=LNG_EDIT?></a></div>
		<div class="category-delete"><a onclick="if (confirm('Are you sure?')) { var f = document.createElement('form'); f.style.display = 'none'; this.parentNode.appendChild(f); f.method = 'POST'; f.action = this.href;var m = document.createElement('input'); m.setAttribute('type', 'hidden'); m.setAttribute('name', '_method'); m.setAttribute('value', 'delete'); f.appendChild(m);var s = document.createElement('input'); s.setAttribute('type', 'hidden'); s.setAttribute('name', 'authenticity_token'); s.setAttribute('value', 'jxe4KrBh9zhiA21N/QRwUaTBOc78a/7hoWXkA9SOIXU='); f.appendChild(s);f.submit(); };return false;" href="<?=BASE_PATH?>grades/destroy/gradeid/<?=$clist['id']?>"><?=LNG_DELETE?></a></div>
      </li>
    <?
		$i++;	
		} ?>
	</ul>
	<?
	} else { ?>
	<div><?=LNG_NO_RECORD_AVAILABLE?></div>
	<?
	} 
	?>

  <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
