<link href="<?=CSS_URL?>subjects/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="Subjects" src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_SUBJECTS?></h1>
  <h3><?=LNG_HOME?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">
  
<div class="box">

  <div class="label-field-pair">
   <label for="student_class"><?=LNG_SELECT_GRADE?>
<img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
   </label>
   <div class="text-input-bg">
  <select onchange="getajax('<?=BASE_PATH?>subjectstemplate/show','?gradeid='+this.value,'subjects');" name="grade_id" id="grade_id"><option value=""><?=LNG_SELECT_A_GRADE?></option>
	<? foreach($this->glist as $glist) { ?>
		<option value="<?=$glist['id']?>"><?=$glist['grade_name']?></option>
		<? } ?></select>
</div></div>

<div id="subjects"></div>
<div style="display: none;" id="modal-box"></div>

<div class="extender"></div>
 </div></div> </div>

      <div class="extender"></div>
<?
if($this->grade_id) { ?>
<script>
	document.getElementById("grade_id").value = '<?=$this->gradeid?>';
	getajax('<?=BASE_PATH?>subjectstemplate/show','?gradeid=<?=$this->gradeid?>','subjects');
	
</script>
<? } else { ?>
<script>
	if(document.getElementById("grade_id").value) {
		getajax('<?=BASE_PATH?>subjectstemplate/show','?gradeid='+document.getElementById("grade_id").value,'subjects');
	}
	
</script>
<? } ?>