<script>
	function modeaction(batch_id,mode)
	{
		if(mode=='Monthly')
		{
			getajax('<?=BASE_PATH?>attendancereport/show','?batch_id='+batch_id+'&mode='+mode,'month');
		}else{
			document.getElementById('month').innerHTML='';
			getajax('<?=BASE_PATH?>attendancereport/report','?batch_id='+batch_id+'&mode='+mode,'report');
		}
		
	}
</script>

<link href="<?=CSS_URL?>attendance_reports/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>attendence/attendence.png">
  <h1><?=LNG_ATTENDANCE_REPORT?></h1>
  <h3><?=LNG_REPORT?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <!-- <li><a href="/student_attendance/advance_search">Advanced</a></li> -->
  </ul>
</div>
<div id="page-yield" style="text-align:left;">

  <div class="label-field-pair">
          <label> <?=LNG_SELECT_A_BATCH?> </label>
    <div class="text-input-bg">
      
        <select onchange="getajax('<?=BASE_PATH?>attendancereport/mode','?batch_id='+this.value,'mode');" name="batch_id" id="batch_id">
			<option value=""><?=LNG_SELECT_A_BATCH?></option>
			<? foreach($this->cblist as $cblist) { ?>
		<option value="<?=$cblist['id']?>"><?=$cblist['grade_name']?> - <?=$cblist['name']?></option>
		<? } ?>
		</select>
      

<img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader"><div class="extender"></div>
    </div>
  </div>

 
  <div id="subject"></div>
  <div id="mode"></div>
  <div id="month"></div>
  <div id="year"></div>
  <div id="report"></div>
</div> </div>

      <div class="extender"></div>
