<?
global $mySession;
//echo"<pre>";print_r($this->studentdetail);exit;
//echo"<pre>";print_r($this->abs_detail);exit;
?>
<link href="<?=CSS_URL?>attendance_reports/student_details.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
  
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>attendence/attendence.png">
  <h1><?=LNG_ATTENDANCE_REPORT?></h1>
  <h3><?=LNG_STUDENT_REPORT?></h3>
 <?php /*?> <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div><?php */?>
</div>

<div id="page-yield">
 	
  <? if(count($mySession->user['userstudentid']) > 1) {		
		?>
			<form method="post" action="<?=BASE_PATH?>attendancereport/reportforparent"><div style="margin: 0pt; padding: 0pt; display: inline;"><input type="hidden" value="BwVDJkXp81PzRlHDNPgqE8xs3LgnL4IH+G5vEg+zGBk=" name="authenticity_token"></div>
				<div class="label-field-pair">
				  <label for="timetable_entry_class_id" style="width:130px; margin-right:30px;"><?=LNG_DETAILED_REPORT_FOR?></label>
				   <img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
				  <div class="text-input-bg">
				  <select onchange="window.location='<?=BASE_PATH?>attendancereport/reportforparent/studentid/'+this.value;" name="timetable_entry[grade_id]" id="timetable_entry_class_id">					
					<? foreach($this->studentlist as $studentlist) { ?>
						<option value="<?=$studentlist['id']?>"<? if(@$studentlist['id']==$this->studentid) { ?> selected="selected"<? } ?>><?=$studentlist['first_name']?> <?=$studentlist['middle_name']?></option>
					<? } ?>
				
				</select>
				  </div>
				</div>
			  </form>
			  <div class="extender"> </div>
		  <div id="student_marks_view"> </div>
		<? 		
	}else{ ?>
	 <div class="label-field-pair">
		<label style="width:250px;"> <?=LNG_DETAILED_REPORT_FOR?> <?=$this->studentdetail['stname']?></label>
	  </div>
    <div class="extender"> </div>  
    <? } ?>
  <table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td style="vertical-align:top; width:100px;">
<div id="sidebar_news_area">
	<div class="sidebar_head">
		<?=LNG_SEMESTER?>
	</div>
	<div>
	<ul>
	<?
		if($this->studentdetail['secondsem']<=time()){
	?>
		<li><a href="<?=BASE_PATH?>attendancereport/reportforparent/year/<?=$this->studentdetail['sem1_start']?>/studentid/<? echo $this->studentdetail['stuid']; ?>/batchid/<? echo $this->studentdetail['batchid']; ?>/semno/2">
			<?=$this->studentdetail['sem1_start']?> Sem 2</a></li>
	<?
		}
	?>
		<li><a href="<?=BASE_PATH?>attendancereport/reportforparent/year/<?=$this->studentdetail['sem1_start']?>/studentid/<? echo $this->studentdetail['stuid']; ?>/batchid/<? echo $this->studentdetail['batchid']; ?>/semno/1">
			<?=$this->studentdetail['sem1_start']?> Sem 1</a></li>
	
		
	<?
		foreach($this->olddetail as $olddetail){
		?>
			<li><a href="<?=BASE_PATH?>attendancereport/reportforparent/year/<?=$olddetail['sem1_start']?>/studentid/<? echo $this->studentdetail['stuid']; ?>/batchid/<?=$olddetail['batchid']; ?>/semno/2">
				<?=$olddetail['sem1_start']?> Sem 2</a></li>
			<li><a href="<?=BASE_PATH?>attendancereport/reportforparent/year/<?=$olddetail['sem1_start']?>/studentid/<? echo $this->studentdetail['stuid']; ?>/batchid/<?=$olddetail['batchid']; ?>/semno/1">
				<?=$olddetail['sem1_start']?> Sem 1</a></li>			
		<?
		}
	?>
	</ul>
	</div>
</div>
	</td>
    <td style="vertical-align:top; ">
	<h4 style="padding:0 0 0 40px; margin:0;"><?=LNG_TOTAL_ABSENTS?> <?=count($this->abs_detail)?></h4>
	<table id="listing" align="center" width="93%">
    <tr class="tr-head">
      <td>
        <?=LNG_DATE?>
      </td>
      <td>
        <?=LNG_STATUS?>
      </td>
      <td>
        <?=LNG_REASON?>
      </td>
    </tr>
    <tr class="blank"></tr>
    <? 
	  foreach($this->abs_detail as $detail) { 
		if($detail['forenoon']==1 && $detail['afternoon']==1)
		{
			$status= 'Fullday';
		} elseif($detail['forenoon']==1)
		{
			$status= 'Forenoon';
		} elseif($detail['afternoon']==1)
		{
			$status= 'Afternoon';
		}
	?>
		<tr class="tr-odd">
        
        <td class="col-2"><?=$detail['monthdate']?></td>
        <td class="col-3"><?=$status?></td>
        <td class="col-2"><?=$detail['reason']?></td>
    
      </tr>
	<? } ?>    
 </table>
 	</td>
  </tr>
</table>

</div> </div>

      <div class="extender"></div>
