
<div class="label-field-pair"><label>
  <?=LNG_SELECT_MONTH_AND_YEAR?>
</label>
<div class="text-input-bg">
<?
	$startfrom = ($this->resdate['st_year'] * 12) + $this->resdate['st_month'] ;

		$j = ($this->resdate['end_year'] * 12) + $this->resdate['end_month'] ;
			//echo $startfrom."<br>".$j;
?>
<select id="month_id" name="month_id"  onchange="getajax('<?=BASE_PATH?>attendancereport/report','?batch_id=<?=$this->batch_id?>&month_id='+this.value,'report');" >
<option value=""><?=LNG_SELECT_A_MONTH?></option>
	
	<?		
		for($i=$startfrom;$i<=$j;$i++){
		$n = $i%12;
		if($n==0){ $n = 12; }
			$y = ($i-$n)/12;
			$month = date('M',mktime(0,0,0,$n,1,$y));
			
	?>
		<option value="<?=$y.'-'.str_pad($n,2,0,STR_PAD_LEFT)?>"><?=$month.'-'.number_format($y,0,'','')?></option>
	<?
		}
	?>
</select>
</div>
</div>
