<script>
function gotoprint()
{
	obj_win = window.open('about:blank', 'new_win','toolbars=no,maximize=no,scrollbars=yes,menubar=no,width=900,height=680,directories=no,resizable=0,screenX=0,screenY=0,left=0,top=0'  ) ; 
 //alert obj_win;
	obj_win.document.write('<html><title>My School</title><link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" rel="stylesheet" type="text/css" /><head>');

	obj_win.document.write('</head>');
	obj_win.document.write('<style type="text/css">   </style>');
	obj_win.document.write('<body><div style="width:850px; " >');

	obj_win.document.write(document.getElementById('printmiddiv').innerHTML);

	obj_win.document.write("</div></body></html>");

	obj_win.document.close();



	obj_win.focus();

	obj_win.print();

	obj_win.close();
}
</script>

<? if(is_array($this->detail) && count($this->detail) > 0) { ?>
<link href="<?=CSS_URL?>attendance_reports/student_details.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
     
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>attendence/attendence.png">
  <h1><?=LNG_ATTENDANCE_REPORT?></h1>
  <h3><?=LNG_STUDENT_REPORT?></h3>
 <?php /*?> <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div><?php */?>
</div>

<div id="page-yield">
  <div class="label-field-pair">
    <label style="width:300px;"><?=LNG_DETAILED_REPORT_FOR?> <?=$this->detail[0]['name']?></label>
  </div>
  <div class="submit-button2">
  <input type="button" value="Print" name="print" class="submit-button" onclick="gotoprint()" />
  </div>
  <?
  tframe_pre();
  ?>
  <div id="printmiddiv">
  <table id="listing" align="center" width="100%">
    <tbody><tr class="tr-head">
      <td>
        <?=LNG_DATE?>
      </td>
      <td>
        <?=LNG_STATUS?>
      </td>
      <td>
        <?=LNG_REASON?>
      </td>
    </tr>
    <tr class="blank"></tr>
    <? $i=1;
	  foreach($this->abs_detail as $detail) { 
		if($detail['forenoon']==1 && $detail['afternoon']==1)
		{
			$status= 'Fullday';
		} elseif($detail['forenoon']==1)
		{
			$status= 'Forenoon';
		} elseif($detail['afternoon']==1)
		{
			$status= 'Afternoon';
		}
	?>
		<tr class="tr-odd">
        
        <td class="col-2"><?=$detail['month_date']?></td>
        <td class="col-3"><?=$status?></td>
        <td class="col-2"><?=$detail['reason']?></td>
    
      </tr>
	<? } ?>    
  </tbody></table>
  </div>
  <?
  tframe_post();
  ?>
</div> </div>

      <div class="extender"></div>
<? } ?>   