<?
global $mySession;
?>
<link href="<?=CSS_URL?>reminder/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>reminder/reminder_small.png">
  <h1><?=LNG_QUESTIONAIRE?></h1>
  <h3><?=LNG_ARCHIVE_LIST?></h3>
  <div id="app-back-button">
  <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>

<? if($mySession->user['usertype']=='A' || $mySession->user['usertype']=='S') { ?>
<div id="inner-tab-menu">
  <ul>
        <li><a href="<?=BASE_PATH?>questionaire"><?=LNG_GENERAL_LIST?></a></li>
		<li><a href="<?=BASE_PATH?>questionaire/create"><?=LNG_CREATE?></a></li>
     <?php /*?>  
	 <li><a href="<?=BASE_PATH?>questionaire/archive"><?=LNG_ARCHIVE?></a></li>
	 <li><a href="<?=BASE_PATH?>reminder/createreminder">Create</a></li><?php */?>
  </ul>
</div>
<? }else{
?>
<div id="inner-tab-menu">
  <ul>
        <li><a href="<?=BASE_PATH?>questionaire"><?=LNG_GENERAL_LIST?></a></li>
  </ul>
</div>
<?
} ?>



<div id="page-yield">

  



  <div id="application-list">
    <table id="listing" align="center" cellpadding="1" cellspacing="1" width="100%">
      <tbody><tr class="tr-head">
        <td>
          To
        </td>
        <td>
          Summary
        </td>
        <td>
          Date
        </td>
      </tr>
      </tr>
	 <tr>
   	   <td></td>
       <td></td>
   		<td></td>
      	<td></td>
    </tr>
	<tr class="tr-even">
        <td>&nbsp;
          
        </td>
        <td>&nbsp;
          
        </td>
        <td>&nbsp;
          
        </td>
      </tr>
      <tr class="tr-blank"></tr>

      
    </tbody></table>
    




  </div>
</div> </div>

      <div class="extender"></div>
    