<?
global $mySession;
?>
<link href="<?=CSS_URL?>reminder/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>reminder/reminder_small.png">
  <h1><?=LNG_QUESTIONAIRE?></h1>
  <h3><?=LNG_GENERAL?></h3>
  <div id="app-back-button">
  <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>

<? if($mySession->user['usertype']=='A' || $mySession->user['usertype']=='S') { ?>
<div id="inner-tab-menu">
  <ul>
        <li><a href="<?=BASE_PATH?>questionaire/archive"><?=LNG_ARCHIVE_LIST?></a></li>
		<li><a href="<?=BASE_PATH?>questionaire/create"><?=LNG_CREATE?></a></li>
     
  </ul>
</div>
<? }else{
?>
<div id="inner-tab-menu">
  <ul>
        <li><a href="<?=BASE_PATH?>questionaire/archive"><?=LNG_ARCHIVE_LIST?></a></li>     
  </ul>
</div>
<?
} ?>



<div id="page-yield">

  



  <div id="application-list">

    <table id="listing" align="center" cellpadding="1" cellspacing="1" width="100%">
      <tbody><tr class="tr-head">
        <td>
          <?=LNG_SLNO?>
        </td>
		<td>
          <?=LNG_TITLE?>
        </td>
        <td>
          <?=LNG_DESCRIPTION?>
        </td>
        <td>
          <?=LNG_DATE?>
        </td>
      </tr>
     <tr>
   	   <td></td>
       <td></td>
   		<td></td>
      	<td></td>
    	</tr>
	 </tr>

		<? $i=1; 
		  foreach($this->ticketlist as $ticketlist) {
		   $m=$i%2; 
				if($m==0)
				{
					$class="tr-odd";	
				}else{
					$class="tr-even";	
				}
		 ?>
		<tr class="<? echo $class; ?>">
        <td class="col-1">
          <? echo $i; ?>
        </td>
		<td class="col-3">
          <a href="<?=BASE_PATH?>questionaire/ticketdetail/ticketid/<?=$ticketlist['id']?>"><?=$ticketlist['title']?></a>
        </td>
        <td class="col-2">
          <?=substr($ticketlist['description'],0,200)?>...
        </td>
        <td class="col-4">
         <?=$ticketlist['dt']?>
        </td>
      </tr>
	  <? } ?>
      <tr class="tr-blank"></tr>

      
    </tbody></table>





  </div>
</div> </div>

      <div class="extender"></div>
    