<link href="<?=CSS_URL?>finance/fees_index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>show_finance.png" alt="">
  <h1>Fees</h1>
  <h3>Manages Fees</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<div id="page-yield">

  
  <div class="box">
  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feescreate">Fees Create</a></div>
    <div class="link-descr">Creates Master Fees and Additional Fees</div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feecollection">Fee collection</a></div>
    <div class="link-descr">Creates new fee collecting dates </div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feessubmissionindex">Fees</a> </div>
    <div class="link-descr">Fee Submission </div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feesstudentstructuresearch">Fees Structure</a> </div>
    <div class="link-descr">Displays fees Structure for student</div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feesdefaulters">Fees Defaulters</a></div>
    <div class="link-descr">Students with fees dues </div>
  </div>
</div>
</div> </div>

      <div class="extender"></div>
    