
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 

<div id="content-header">
    <img alt="" src="<?=IMAGES_URL?>show_finance.png">
  <h1>Income &amp; Expenses</h1>
  <h3>Fees Categories</h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back" border="0"></a>
  </div>
</div>

<div id="page-yield">
 
  <div id="student-category-form">
    
<div class="box">
<form method="post" action="<?=BASE_PATH?>finance/feescategories/">

<div class="label-field-pair">
  <label> Enter new Category : </label>
<div class="text-input-bg">
<?php echo $this->form->category_name?></div>
  </div>
  <input value="Save" name="commit" class="submit_button" type="submit">

</form>
</div>

  </div>
  <br><br>

  <div id="student-category-list">
    
<ul id="category-list">  
        <ul id="category-list">  
      <?
	  foreach($this->clist as $clist) { ?>
      <li class="listodd">
        <div class="category-name"><?=$clist['name']?></div>
        <div class="category-edit"><a href="<?=BASE_PATH?>finance/feescategoriesedit/catid/<?=$clist['id']?>">Edit</a> </div><div class="category-delete"><a href="<?=BASE_PATH?>finance/feescategories/mode/delete/catid/<?=$clist['id']?>">Remove</a></div>
      </li>
     
      <? 
	  }
	  ?>
</ul>
     
      </ul>

  </div>

</div>
 </div>

      <div class="extender"></div>
