
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="" src="<?=IMAGES_URL?>show_finance.png">
  <h1>Income &amp; Expenses</h1>
  <h3>Manage Income &amp; Expenses</h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="page-yield">
  
  
  <div id="box">

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/manage">Manage Fees</a> </div>
    <div class="link-descr">Manages Student Fees</div>
  </div>
  
  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feessubmissionindex">Fees Submission</a> </div>
    <div class="link-descr">Fee Submission </div>
  </div>
  
  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feesdefaulters">Fees Defaulters</a></div>
    <div class="link-descr">Students with fees dues </div>
  </div>
  
<?php /*?>
  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/categories">Category</a> </div>
    <div class="link-descr">Manages Category </div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/transactions">Transactions</a> </div>
    <div class="link-descr">Manages expense and income </div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/donation">Donations</a></div>
    <div class="link-descr">Creates new donations</div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/automatictransactions">Auto transactions</a></div>
    <div class="link-descr">Add automatic transactions</div>
  </div>
  
    <div class="link-box">
      <div class="link-heading"><a href="<?=BASE_PATH?>finance/payslipindex">Payslip</a></div>
      <div class="link-descr">Employee Payslips </div>
    </div>
  

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/assetliability"> Asset liability management</a></div>
    <div class="link-descr"> Asset liability management</div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>xml"> Export</a></div>
    <div class="link-descr"> Creates xml import file</div>
  </div>

<?php */?> 
 </div>
</div> </div>

      <div class="extender"></div>
