
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>show_finance.png" alt="">
  <h1>Income & Expenses</h1>
  <h3>Manage Fees</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>
<div id="page-yield">
  

    <div id="box">

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feescategories">Fees Categories</a></div>
    <div class="link-descr">Fees Categories</div>
  </div>

  <div class="link-box">
    <div class="link-heading"><a href="<?=BASE_PATH?>finance/feesstructure">Fees Structure</a></div>
    <div class="link-descr">Manage Fees Structure</div>
  </div>
  
  
</div>
</div> </div>

      <div class="extender"></div>
    