
<div class="label-field-pair">
  <label><?=LNG_SELECT_A_STUDENT?> </label>
 
<div class="text-input-bg">
	<select id="student_list" name="student_list" onchange="getajax('<?=BASE_PATH?>finance/paystudentfees','?batch_id=<?=$this->batch_id?>&student_id='+this.value,'pay_fees');">
		<option value=""><?=LNG_SELECT_STUDENT?></option>
	<? if(isset($this->studentlist) && count($this->studentlist) > 0) { ?>
	  <? $i=1; 
	  foreach($this->studentlist as $studentlist) {   		
	   ?>
			<option value="<?=$studentlist['sid']?>"><?=$studentlist['sname']?></option>
		<? $i++; } ?>
	<? } ?>	
	</select>
</div> </div>