<link href="<?=CSS_URL?>calendar/index.css?1313586643" media="screen" rel="stylesheet" type="text/css"/>
<div id="side_bar">
<div id="sidebar_news_area">
</div>
</div>
<div id="content">
<div id="tooltip_box" style="float:right;">
<img alt="Loader" id="loader" src="<?=IMAGES_URL?>loader.gif?1313586643" style="display: none; float:left;" align="absmiddle" border="0">
<div id="tooltip_header">
</div>
</div>
<div id="calendar"></div>
</div>
<div class="extender"></div>
<script>
getajax('<?=BASE_PATH?>calendar/show/nextmonth/<?=$this->y?>-<?=$this->m?>-1','','calendar');
</script>
