
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="Exam" src="<?=IMAGES_URL?>examination/show_exam.png">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_GRADING_LEVELS?></h3>
  <div id="app-back-button">
      <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>grades"><?=LNG_GRADES?></a></li>
  </ul>
</div>
<div id="page-yield">

    

 <div>
   <div class="label-field-pair">
   <label for="student_class"><?=LNG_BATCHES?>
<img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
   </label>
   <div class="text-input-bg">
   <select onchange="getajax('<?=BASE_PATH?>gradinglevels/show', '?batch_id='+this.value,'grading-levels')" name="batch_id" id="batch_id">
   <option value="0"><?=LNG_COMMON?></option>
  <?
	foreach($this->cblist as $cblist) { ?>
	<option value="<?=$cblist['id']?>"><?=$cblist['grade_name']?> - <?=$cblist['name']?></option>
  <? } ?>
  </select>
	  
   </div></div>


<div id="grading-levels">

</div>
<div style="display: none;" id="modal-box"></div>


</div>
    </div>
 </div>

      <div class="extender"></div>

<script>
batchid = document.getElementById("batch_id").value;
getajax('<?=BASE_PATH?>gradinglevels/show', '?batch_id='+batchid,'grading-levels');
</script>