<div id="content_wrapper">
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
    <img alt="Grades" src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_HOME?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

  

  <div id="box">

    <div class="link-box">
      <div class="link-heading"><a href="<?=BASE_PATH?>grades/manageclass"><?=LNG_MANAGE_GRADES?></a> </div>
      <div class="link-descr"><?=LNG_MANAGE_CREATE_GRADES?></div>
    </div>
    <div class="link-box">
      <div class="link-heading"><a href="<?=BASE_PATH?>grades/managebatches"><?=LNG_MANAGE_BATCHES?></a>  </div>
      <div class="link-descr"><?=LNG_MANAGE_ACTIVE_BATCHES?></div>
    </div>

    <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
    </div>