<link href="<?=CSS_URL?>grades/manage_batches.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
   <img src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_MANAGE_BATCHES?></h3>
  <div id="app-back-button">
  <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<?php /*?><div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>gradinglevels">Grading system</a></li>
    <li><a href="<?=BASE_PATH?>batchtransfers">Batch transfers</a></li>
  </ul>
</div><?php */?>
<div id="page-yield">
    
<div>
<div class="label-field-pair">
   <label for="student_class"><?=LNG_SELECT_GRADE?>
<img border="0" align="absmiddle" style="display: none;" src="<?=IMAGES_URL?>loader.gif?<?=UPDATE_KEY?>" id="loader" alt="Loader">
   </label>
   <div class="text-input-bg">
  <select onchange="getajax('<?=BASE_PATH?>grades/updatebatch','?grade_name='+this.value,'update_batch');" name="grade_name" id="grade_name"><option value=""><?=LNG_SELECT_A_GRADE?></option>
<?
foreach($this->classeslist as $clist) { ?>
<option value="<?=$clist['id']?>"><?=$clist['grade_name']?></option>
<? } ?>
</select>
</div></div>

<div id="update_batch"></div>
<div class="extender"></div>
 </div></div> </div>

      <div class="extender"></div>
