<div id="content_wrapper">
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="Exam" src="<?=IMAGES_URL?>examination/show_exam.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_NEW?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

  

  <div id="box">
    <div class="bread_crumb">
      <a href="<?=BASE_PATH?>grades"><?=LNG_GRADES?></a> &raquo; <?=LNG_NEW?>
    </div>

    <form method="post" id="new_class" class="new_class" action="<?=BASE_PATH?>grades/new">
	
	  <div id="necessary-field-notification"> <?=LNG_FIELDS_MARKED_WITH?> <span class="necessary-field">*</span> <?=LNG_MUST_BE_FILLED?></div>
      <div class="label-field-pair">
        <div class="label-container"><label for="class_class_name"><?=LNG_GRADE_NAME?> <span class="necessary-field">*</span></label></div>
        <div class="input-container"><?php echo $this->form->grade_name?></div>
      </div>

      <?php /*?><div class="label-field-pair">
        <div class="label-container"><label for="class_section_name">Section name</label></div>
        <div class="input-container"><?php echo $this->form->section_name?></div>
      </div><?php */?>

      <div class="label-field-pair">
        <div class="label-container"><label for="class_code"><?=LNG_CODE?> <span class="necessary-field">*</span></label></div>
        <div class="input-container"><?php echo $this->form->grade_code?></div>
      </div>

      <h4><?=LNG_INITIAL_BATCH_DETAIL?></h4>

        <div class="label-field-pair">
          <div class="label-container"><label for="class_batches_attributes_0_name"><?=LNG_NAME?> <span class="necessary-field">*</span></label></div>
          <div class="input-container"><?php echo $this->form->batches_attributes?></div>
        </div>
	    <div class="label-field-pair">
          <div class="label-container"><label for="class_batches_attributes_0_name">Class Teacher <span class="necessary-field">*</span></label></div>
          <div class="text-input-bg"><?php echo $this->form->batches_employee_id?></div>
        </div>

        <div class="label-field-pair">
          <div class="label-container"><label for="class_batches_attributes_0_start_date"><?=LNG_START_DATE?> <span class="necessary-field">*</span></label></div>
          <div class="input-container">
		  <div style="float:left"><?php echo $this->form->batches_attributes_startdate?></div><div style="float:left; padding-left:5px; padding-top:10px">
		  <img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('batches_attributes_startdate'), {year_range:10});" class="calendar_date_select_popup_icon" alt="Calendar"></div></div>
        </div>
		
		<div class="label-field-pair">
          <div class="label-container"><label for="class_batches_attributes_0_start_date"><?=LNG_SECONT_SEM_START_DATE?> <span class="necessary-field">*</span></label></div>
          <div class="input-container">
		  <div style="float:left"><?php echo $this->form->batches_attributes_sec_sem_start?></div><div style="float:left; padding-left:5px; padding-top:10px">
		  <img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('batches_attributes_sec_sem_start'), {year_range:10});" class="calendar_date_select_popup_icon" alt="Calendar"></div></div>
        </div>

        <div class="label-field-pair">
          <div class="label-container"><label for="class_batches_attributes_0_end_date"><?=LNG_END_DATE?> <span class="necessary-field">*</span></label></div>
          <div class="input-container">
		  <div style="float:left"><?php echo $this->form->batches_attributes_enddate?></div><div style="float:left; padding-left:5px; padding-top:10px"><img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('batches_attributes_enddate'), {year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div></div>
        </div>

      

      <input type="submit" value="<?=LNG_SAVE?>" name="commit" class="submit_button">

    </form>

    <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
    </div>