
<link href="<?=CSS_URL?>grades/show.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
    <img src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_GRADES?></h1>
  <h3><?=LNG_SHOW?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>batches/new/gradeid/<?=$this->gradeid?>"><?=LNG_NEW_BATCH?></a> </li>
        
    <li style="width:150px;">
      <a href="<?=BASE_PATH?>subjects/index/gradeid/<?=$this->gradeid?>" class="drops" id="link_one"><?=LNG_MANAGE_SUBJECTS?></a>
      <?php /*?><ul id="box_one" class="scriptaculously" style="display:none;">
        <li><a href="<?=BASE_PATH?>batchtransfers/subjecttransfer/batchid/1">Subjects</a></li>
        <li><a href="<?=BASE_PATH?>electivegroups/index/batchid/1">Electives</a></li>
        <li><a href="<?=BASE_PATH?>batches/assigntutor/batchid/1">Assign Tutor</a></li>
      </ul><?php */?>
    </li>
  </ul>
</div>
<div id="page-yield">
  
  <div class="box">
  <form name="grades" action="" method="post" style="display: inline;">
        <div class="bread_crumb">
        <a href="<?=BASE_PATH?>grades"><?=LNG_GRADES?></a> &raquo;
        <?=$this->classdetail[0]['grade_name'];?>
        </div>


    
	<? 
	if(isset($this->batcheslist) && is_array($this->batcheslist) && count($this->batcheslist) > 0)
	{ ?>
	<ul id="category-list">
	<?
	foreach($this->batcheslist as $blist)
	{ 
		
		?>
      
        <li class="listodd">
          <div class="batch-name">
		  		<a href="<?=BASE_PATH?>batches/show/gradeid/<?=$this->gradeid?>/batchid/<?=$blist['id']?>"><?=$this->classdetail[0]['grade_name'];?> - <?=$blist['name']?></a>
			</div>		  	
			<?
				if($blist['ename']){
				?>
				<div class="teacher-name"><a href="<?=BASE_PATH?>employee/profile/profileid/<?=$blist['empid']?>"><?=$blist['ename']?></a></div>
				<?
				}
			?>
			 
		   <div class="category-edit"> <a href="<?=BASE_PATH?>batches/edit/gradeid/<?=$this->gradeid?>/batchid/<?=$blist['id']?>"><?=LNG_EDIT?></a></div>
		  	<div class="category-delete">
		  	<a onclick="if (confirm('Are you sure?')) { return true; };return false;" href="<?=BASE_PATH?>batches/destroy/gradeid/<?=$this->gradeid?>/batchid/<?=$blist['id']?>">
		  		<?=LNG_DELETE?>
			</a>
			</div>
         <?
	} ?>
	</ul>
	<?
	} else { ?>
	<div><p class="flash-msg"> <?=LNG_NO_BATCHES_AVAILABLE?> </p></div>
	<?
	} 
	?>
<div class="submit-button" style="float:left; width:250px">
			
			<input type="button" class="submit-button" style="margin-top:0" name="commit" onclick="this.form.action='<?=BASE_PATH?>batches/exportxls/gradeid/<?=$this->gradeid?>'; this.form.submit()" value="<?=LNG_EXPORT?>">
		</div>
    <div class="extender"></div>
	</form>
  </div>
</div>
 </div>

      <div class="extender"></div>
