
<link href="<?=CSS_URL?>weekday/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="content"> 
<div id="content-header">
   <img src="<?=IMAGES_URL?>show_timetable.png">
  <h1><?=LNG_TIMETABLE?></h1>
  <h3><?=LNG_WEEKDAYS?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

  

    <div id="box" style="text-align:left;">
  <div class="label-field-pair">
    <label for="timetable_entry_class_id"><?=LNG_SELECT_A_BATCH?><?=LNG_SEPERATOR_1?></label>
    <div class="text-input-bg"><select onchange="getajax('<?=BASE_PATH?>weekday/week/','?batch_id='+this.value,'weekdays')" name="selbatchcid" id="selbatchcid"><option value="0" ><?=LNG_SELECT_A_BATCH?></option>
<?
foreach($this->cblist as $cblist) { ?>
<option value="<?=$cblist['id']?>"><?=$cblist['grade_name']?> - <?=$cblist['name']?></option>
<? } ?></select>

      </div>
  </div>
<div id="weekdays">

</div>
<div style="display: none;" id="modal-box"></div>
     <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
<?
	if($this->batchid){
		?>
			<script>
				document.getElementById('selbatchcid').value='<?=$this->batchid?>';
				getajax('<?=BASE_PATH?>weekday/week/','?batch_id=<?=$this->batchid?>','weekdays');
			</script>
		<?
	}
?>