<?
global $mySession;
?><!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>My School</title>
<link href="<?=CSS_URL?>application.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
  <link href="<?=CSS_URL?>_layouts/login.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
  <script src="<?=JS_URL?>prototype.js?<?=UPDATE_KEY?>" type="text/javascript"></script>
<script src="<?=JS_URL?>effects.js?<?=UPDATE_KEY?>" type="text/javascript"></script>
<script src="<?=JS_URL?>dragdrop.js?<?=UPDATE_KEY?>" type="text/javascript"></script>
<script src="<?=JS_URL?>controls.js?<?=UPDATE_KEY?>" type="text/javascript"></script>

<script src="<?=JS_URL?>application.js?<?=UPDATE_KEY?>" type="text/javascript"></script>
</head>

<body>
  
<div id="wrapper">
<div style="width:980px">
<div id="errorDiv" >
<?php  
	if(isset($mySession->errorMsg)){ 
		echo errorMsg($mySession->errorMsg);
		unset($mySession->errorMsg); 
	} 
	if(isset($mySession->sucMsg)){ 
		echo sucessMsg($mySession->sucMsg);
		unset($mySession->sucMsg); 
	} 
	if(isset($mySession->warningMsg)){ 
		echo warningMsg($mySession->warningMsg);
		unset($mySession->warningMsg); 
	}
	?>
</div>
</div>
  <div id="top_logo">
    

    <img src="<?=IMAGES_URL?>application/logo.png"/>
    
  </div>

  <?php /*?><div id="help_top">
    <div id="help_link"><a href="http://www.dmadsinfotech.com/myschool/help/" target="_blank">Help!</a></div>

  </div><?php */?>
<? echo $this->layout()->content; ?>
 

    <div id="footer">

      <div id="footer_logo">
            <div id="powered_by">
          <?=LNG_POWERED_BY?> <a href="http://www.dmadsinfotech.com" target="_blank">DMads Infotech</a>
        </div>
          <a href="http://www.dmadsinfotech.com" target="_blank" class="footer-logo"></a>
          
      </div>
    </div>

<script type="text/javascript">
document.getElementById('login_id').focus();
 </script>
</div>
</body>
</html>

