<link href="<?=CSS_URL?>event/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>manage_news/manage_news_logo.png">
  <h1><?=LNG_EVENTS?></h1>
  <h3><?=LNG_STEP1_EVENT_CREATE?></h3>
  <div id="app-back-button">
       <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="page-yield">
  
  <form method="post" action="<?=BASE_PATH?>event/editevent/eventid/<?=$this->eventid?>">
    
    <div class="label-field-pair">
      <label for="start-date"><?=LNG_START_DATE?></label>
      <div class="text-input-bg">
	  <?php echo $this->form->events_start_date?>
	   <img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $(this).previous(), {time:true, year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
    </div>
    <div class="label-field-pair">
      <label for="end-date"><?=LNG_END_DATE?></label>
      <div class="text-input-bg">
	  <?php echo $this->form->events_end_date?> 
	  <img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $(this).previous(), {time:true, year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div>
    </div>
    <div class="label-field-pair">
      <label for="title"><?=LNG_TITLE?></label>
      <div class="text-input-bg"><?php echo $this->form->events_title?></div>
    </div>
    <div class="label-field-pair">
      <label for="description">  Description :</label>
    </div>
    <?php echo $this->form->events_description?>
    <div class="label-field-pair">
      <label for="is-holiday"><?=LNG_IS_HOLIDAY?></label>
     
	  <input type="checkbox" value="1" name="is_holiday" id="events_is_holiday" <? if($this->eventdata['is_holiday']) { ?> checked="checked"<? } ?>>
    </div>
    <div class="label-field-pair">
      <label for="end-date"> <?=LNG_EVENT_COMMON_TO_ALL?></label>
    
	  <input type="checkbox" value="1" name="is_common" id="events_is_common" <? if($this->eventdata['is_common']) { ?> checked="checked"<? } ?>>
    </div>
    <input type="submit" value="<?=LNG_UPDATE_EVENT?>" name="commit" id="events_submit">
  </form>
</div>
 </div>

      <div class="extender"></div>
