<link href="<?=CSS_URL?>event/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
    
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>manage_news/manage_news_logo.png">
  <h1><?=LNG_EVENTS?></h1>
  <h3><?=LNG_STEP1_EVENT_CREATE?></h3>
  <div id="app-back-button">
       <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>
<div id="page-yield">
  
  
  
  <form style="text-align:left;" method="post" action="<?=BASE_PATH?>event"><div style="margin: 0pt; padding: 0pt; display: inline;">
  <input type="hidden" value="BwVDJkXp81PzRlHDNPgqE8xs3LgnL4IH+G5vEg+zGBk=" name="authenticity_token"></div>
    
	<div id="necessary-field-notification"> <?=LNG_FIELDS_MARKED_WITH?> <span class="necessary-field">*</span> <?=LNG_MUST_BE_FILLED?></div>
	
    <div class="label-field-pair">
      <label for="start-date"><?=LNG_START_DATE?> <span class="necessary-field">*</span></label>
      <div class="text-input-bg">
	  <div style="float:left"><?php echo $this->form->events_start_date?></div><div style="float:left; padding-left:5px; padding-top:10px">
	   <img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('events_start_date'), {time:true, year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div></div>
    </div>
    <div class="label-field-pair">
      <label for="end-date"><?=LNG_END_DATE?> <span class="necessary-field">*</span></label>
      <div class="text-input-bg">
	  <div style="float:left"><?php echo $this->form->events_end_date?></div><div style="float:left; padding-left:5px; padding-top:10px">
	  <img style="border: 0px none; cursor: pointer;" src="<?=IMAGES_URL?>calendar_date_select/calendar.gif?<?=UPDATE_KEY?>" onclick="new CalendarDateSelect( $('events_end_date'), {time:true, year_range:10} );" class="calendar_date_select_popup_icon" alt="Calendar"></div></div>
    </div>
    <div class="label-field-pair">
      <label for="title"><?=LNG_TITLE?> <span class="necessary-field">*</span></label>
      <div class="text-input-bg"><?php echo $this->form->events_title?></div>
    </div>
    <div class="label-field-pair">
      <label for="description">  <?=LNG_DESCRIPTION?></label>
    </div>
    <?php echo $this->form->events_description?>
    <div class="label-field-pair">
      <label for="is-holiday"><?=LNG_IS_HOLIDAY?></label>
      <input type="hidden" value="0" name="is_holiday">
	  <input type="checkbox" style="border:none; background:none;" value="1" name="is_holiday" id="events_is_holiday">
    </div>
    <div class="label-field-pair">
      <label for="end-date"> <?=LNG_EVENT_COMMON_TO_ALL?></label>
      <input type="hidden" value="0" name="is_common">
	  <input type="checkbox" value="1" style="border:none; background:none;" name="is_common" id="events_is_common">
    </div>
    <input type="submit" value="<?=LNG_CREATE_EVENT?>" name="commit" id="events_submit">
  </form>
</div>
 </div>

      <div class="extender"></div>
