<?
global $mySession;
?>
<link href="<?=CSS_URL?>event/show.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
    
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>manage_news/manage_news_logo.png">
  <h1><?=LNG_EVENTS?></h1>
  <h3><?=LNG_STEP2_CONFIRMATION?></h3>
  <div id="app-back-button">
    <a href="<?=BASE_PATH?>event"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" border="0"></a>
  </div>
</div>
<div id="page-yield">



    <div class="detail-box">
      <div class="label"> <?=LNG_TITLE?> <?=LNG_SEPERATOR_1?></div>
      <div class="description">
       <?php echo $this->eventData['title']; ?>
      </div>
    <div class="extender"></div>
      <div class="label"><?=LNG_DESCRIPTION?> <?=LNG_SEPERATOR_1?></div>
      <div class="description">
       <?php echo $this->eventData['description']; ?>
      </div>
    <div class="extender"></div>
      <div class="label">
        <?=LNG_START_DATE?> <?=LNG_SEPERATOR_1?></div>
      <div class="description">
        <?php echo $this->eventData['start_date']; ?>
      </div>
    <div class="extender"></div>
      <div class="label"> <?=LNG_END_DATE?> <?=LNG_SEPERATOR_1?></div>
      <div class="description">
       <?php echo $this->eventData['end_date']; ?>
      </div>
    <div class="extender"></div>
    </div>
   
    
    
    <div class="extra"> 
	<? if($this->eventData['is_common']) { ?>
         <?=LNG_THIS_EVENT_IS_COMMON_ACROSS_ALL_CLASSES?> <br><br />  
    <? } else { ?>
	<div>
		<div class="course-select">
		<? if(is_array($this->batchlist) && count($this->batchlist) > 0 ) {?>
		
			<span class="title"><?=LNG_COURSES_ASSOCIATED?><?=LNG_SEPERATOR_1?></span>
			<div>
			<ul id="category-list" style="text-align:left;">
				<?
				foreach($this->batchlist as $blist) { ?>
					<li class="listodd">
					<div class="category-name" style="width:220px"><?=$blist['grade_name']?> - <?=$blist['bname']?></div>
					<div class="category-edit"><a href="<?=BASE_PATH?>event/removebatch/batch_eventid/<?=$blist['id']?>"><?=LNG_REMOVE?></a></div>
					</li>
				<? 
				} ?>
				
			</ul>
			</div>
			<a onclick="getajax('<?=BASE_PATH?>event/selectcourse/eventid/<?=$this->eventid?>', '','select-option')" href="#"><?=LNG_SELECT_MORE_COURSES?></a><br>

		<? } else { ?><span class="title"><?=LNG_NO_CLASS_SELECTED_FOR_THIS_EVENT?> <?=LNG_SEPERATOR_1?></span>
		<a onclick="getajax('<?=BASE_PATH?>event/selectcourse/eventid/<?=$this->eventid?>', '','select-option')" href="#">Select Class</a>
		<? } ?>
		</div>
	</div>
	<div id="select-option"></div>
	<? } ?>
    
    <a href="<?=BASE_PATH?>event/confirmevent/eventid/<?=$this->eventid?>" class="create">Confirm</a>  <a href="<?=BASE_PATH?>event/cancelevent/eventid/<?=$this->eventid?>" class="create"><?=LNG_CANCEL?></a>
    
    </div>
</div>
    
 </div>

      <div class="extender"></div>
    