<link href="<?=CSS_URL?>user/change_password.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>edit_users/edit_users_logo.jpg">
  <h1>Update Password</h1>
  <h3>Change your password</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<script>
function vali()
{
	if(document.getElementById("user_new_password").value=='') {
		alert("Please enter new password");
		return false;
	}
	if(document.getElementById("user_confirm_password").value=='') {
		alert("Please enter confirm password");
		return false;
	}
	if(document.getElementById("user_new_password").value!=document.getElementById("user_confirm_password").value) {
		alert("Confirm password should be same");
		return false;
	}
	return true;
}
</script>
<div id="page-yield">
<? if($this->chps) { ?>  
  <div id="changepw-form">
    <form action="<?=BASE_PATH?>user/changepassword" method="post" onsubmit="return vali()">
<div class="box">

<?php /*?><div class="label-field-pair">
    <div class="label-container"><label>Old password:</label> </div>
    <div class="input-container"> <input id="user_old_password" name="user[old_password]" size="30" type="password"></div>
   </div><?php */?>
    <div class="label-field-pair">
    <div class="label-container"><label>New password :</label> </div>
    <div class="input-container"><input id="user_new_password" name="user_new_password" size="30" type="password"></div>
   </div>
    <div class="label-field-pair">
    <div class="label-container"><label>Confirm password :</label> </div>
    <div class="input-container"><input id="user_confirm_password" name="user_confirm_password" size="30" type="password"></div>
   </div>
       <input class="submit_button" name="commit" value="Update" type="submit">    
  </div>
  </form></div>
<? } else { ?>

<? } ?>
</div> </div>

      <div class="extender"></div>
    