<?
	$db=new Db();
?>
<script type="text/javascript">
function divremove(no)
{
	document.getElementById("msgdiv"+no).style.display="none";
}
      /***********************************************
       * Dynamic Countdown script- © Dynamic Drive (http://www.dynamicdrive.com)
       * This notice MUST stay intact for legal use
       * Visit http://www.dynamicdrive.com/ for this script and 100s more.
       ***********************************************/
      var anylinkmenu1={divclass:'anylinkmenu', inlinestyle:'', linktarget:''} //First menu variable. Make sure "anylinkmenu1" is a unique name!
      anylinkmenu1.items = [
        ["<?=LNG_EXAMS?>", "<?=BASE_PATH?>examgroups/index"],        
        ["<?=LNG_ADD_NEW_EXAM?>", "<?=BASE_PATH?>exam/updateexamform"],        
      ]
      anylinkmenu.init("menuanchorclass");
	  
	  function getajax(urlval,param,elm_id,popupbox)
		{
			
			params = param.replace("?","");
			if ( params ) {
				// If it's a function
				if ( jQuery.isFunction( params ) ) {
					// We assume that it's the callback
					callback = params;
					params = undefined;
					urlval=urlval+param;
				// Otherwise, build a param string
				} else if ( typeof params === "object" ) {
					params = jQuery.param( params, jQuery.ajaxSettings.traditional );
					type = "POST";
				}
			}
			if(urlval!='')
			{
				
				document.getElementById(elm_id).innerHTML="<img src='<?=IMAGES_URL?>load.gif' border='0'>";
				jQuery.ajax({ url: urlval,
				type: "POST",
				data : params,
				success: function(data){			
					if(popupbox==2) {
						eval(data);
					} else if(popupbox==1) {
						jQuery("#"+elm_id).html(data);
						Modalbox.show($(elm_id), {title: '', width: 500});
					} else {
						jQuery("#"+elm_id).html(data);
					}
				}});
			}
		}
    </script>
<div id="header_bg">
	<table width="1000" border="0" cellspacing="0" cellpadding="0" style="background-color:transparent">
	  <tr>
		<td>
			<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:transparent">
			  <tr>
				<td height="40"> 
					<div id="school_name" ><?=$mySession->user['schoolname']?></div>		  
					<div style="float:right; font-size:13px; font-weight:bold; width:420px;">
				<table width="100%" border="0" cellspacing="0" cellpadding="0" style="-moz-border-radius:0px; background:none; padding:0px;">
				 <tr>
					
					<td style="color:#FFFFFF" height="27">
					<?
					if($mySession->setlanguage=='1'){
					?>
					 <?=LNG_WELCOME_MESSAGE1?><?=LNG_SEPERATOR_1?>
					 <a class="welcome_msg" href="<?=BASE_PATH?>user/profile/profileid/<?=$mySession->user['userid']?>"><?=$mySession->user['fname']?></a> &nbsp;|&nbsp;
					 <?
					 }else{
					 ?>
						<a class="welcome_msg" href="<?=BASE_PATH?>user/profile/profileid/<?=$mySession->user['userid']?>"><?=$mySession->user['fname']?></a>
						<?=LNG_SEPERATOR_1?><?=LNG_WELCOME_MESSAGE1?>
			 &nbsp;|&nbsp;
					 <?
					 }
					 ?>
					</td>
					
					<td style="color:#FFFFFF;">
					<div style="float:left" ><a class="welcome_msg" href="<?=BASE_PATH?>reminder" title="<?=LNG_MESSAGES?>"><img src="<?=IMAGES_URL?>message.gif" border="0" alt="<?=LNG_MESSAGES?>" /></a></div><div style="float:left">(<?=$mySession->msgcont?>)</div>&nbsp;|&nbsp;
					</td>
					
					<?
						$qry = "select * from `request_student` where to_school='".$mySession->user['schoolid']."'";
						$record=$db->runQuery("$qry");
						$this->view->record=$record;
						
						if(count($record)>0){
							?>					
							<td style="color:#FFFFFF;">
								<div style="float:left" title="<?=LNG_STUDENT_REQUEST?>">
									<a class="welcome_msg" href="<?=BASE_PATH?>student/studentrequest">
										<img src="<?=IMAGES_URL?>Icon_Question.gif" height="18" border="0" alt="<?=LNG_QUESTIONAIRE?>" />
									</a>
								</div>&nbsp;|&nbsp;
							</td>					
							<?
						}
					?>
					
					<?php /*?><td style="color:#FFFFFF;">
					<div style="float:left" title="<?=LNG_QUESTIONAIRE?>"><a href="<?=BASE_PATH?>questionaire" title="<?=LNG_QUESTIONAIRE?>"><img src="<?=IMAGES_URL?>Icon_Question.gif" height="18" border="0" alt="<?=LNG_QUESTIONAIRE?>" /></a></div><div style="float:left">(<?=$mySession->msgcont?>)</div>&nbsp;|&nbsp;
					</td><?php */?>
					<td style="color:#FFFFFF;">
					<a class="welcome_msg" href="<?=BASE_PATH?>user/changepassword"><?=LNG_CHANGE_PASSWORD?></a>&nbsp;|&nbsp;
					</td>
					<td style="color:#FFFFFF;"><a class="welcome_msg" href="<?=BASE_PATH?>index/logout"><?=LNG_LOGOUT?></a> 
					
					</td>
					
					<?php /*?><td style="width:70px" >&nbsp;
					<div style="position:absolute; top:0px; right:8px; display:none;">
					<?
					if($mySession->setlanguage=='2'){
					?>
							<a class="welcome_msg" href="#" style="color:#000000; text-decoration:none;" onclick="getajax('<?=BASE_PATH?>index/changelanguage/lngid/1','','school_name',2)"><img src="<?=IMAGES_URL?>lng_en.png" border="0" /></a>
					<?
					} else {
					?>
							<a class="welcome_msg" href="#" style="color:#000000; text-decoration:none;" onclick="getajax('<?=BASE_PATH?>index/changelanguage/lngid/2','','school_name',2)"><img src="<?=IMAGES_URL?>lng_ar.png" border="0" /></a>
					<?
					}
					?>
					</div>
					</td><?php */?>
						  </tr>
					</table>
				  </div>
				</td>
			  </tr>
			  <tr>
				<td>
					<div id="header">
						<div id="main-menu">
							<? include("menu.phtml"); ?>
						</div>					
				  </div>
				</td>
			  </tr>
			</table>
		</td>
	  </tr>
	</table>
</div>