<link href="<?=CSS_URL?>user/user_change_password.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>HR/hr_detail.png">
  <h1><?=LNG_ADMINISTRATOR?></h1>
  <h3><?=LNG_CHANGE_PASSWORD?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>

<div id="page-yield">

  <?php /*?><div id="student_profile_heading">



    <div id="student_main_info">
      <span class="name"> <?=$detail['first_name']?> <?=$detail['last_name']?>,  </span>
      <span class="course"> <?=LNG_SCHOOL?> : <?=$detail['schoolname']?>, </span>&nbsp;
      <span class="adm"> <?=LNG_USERNAME?> : <?=$detail['username']?> </span>
    </div>

    <div class="extender"> </div>

  </div><?php */?>

  

  <div id="changepw-form">
    <form action="<?=BASE_PATH?>admin/changepassword" method="post">
	<div style="margin: 0pt; padding: 0pt; display: inline;">
	<input name="authenticity_token" value="tHbPp2Cg/qRHjLmjl0uDWsbyac+CvbhBWywzVzfqUw0=" type="hidden"></div>

      <div class="label-field-pair">
        <label for="course_section"><?=LNG_NEW_PASSWORD?></label>
        <div class="text-input-bg"> <input id="new_password" name="new_password" size="30" type="password"> </div>
      </div>

      <div class="label-field-pair">
        <label for="course_grade"><?=LNG_CONFIRM_PASSWORD?></label>
        <div class="text-input-bg"> <input id="confirm_password" name="confirm_password" size="30" type="password"></div>
      </div>

      <div id="submit-button">
        <input class="user_submit_button" name="commit" value="<?=LNG_UPDATE?>" type="submit">
      </div>

    </form>
  </div>

</div> </div>

      <div class="extender"></div>