<?
$detail=$this->detail[0];
?>

<link href="<?=CSS_URL?>user/profile.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>HR/hr_detail.png">
  <h1><?=LNG_ADMINISTRATOR?></h1>
  <h3><?=LNG_INFORMATION?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>


  <div id="inner-tab-menu">
    <ul>
		<li><a href="<?=BASE_PATH?>admin/changepassword"><?=LNG_CHANGE_PASSWORD?></a></li>
		<li><a href="<?=BASE_PATH?>admin/config"><?=LNG_CONFIGURATION?></a></li>
	</ul>
  </div>


<div id="page-yield">

  

  <div id="profile_view">
	<div class="profile_info_label"><?=LNG_NAME?></div>
    <div class="profile_info_text"><?=$detail['first_name']?></div>
	
    <div class="profile_info_label2"><?=LNG_USERNAME?></div>
    <div class="profile_info_text2"><?=$detail['username']?></div>

    <div class="profile_info_label"><?=LNG_EMAIL?></div>
    <div class="profile_info_text"><?=$detail['email']?></div>
    <div class="extender"></div>
  </div>

  
    <div class="submit-buttons">

     <a href="<?=BASE_PATH?>admin/edit" class="user_button"><?=LNG_EDIT?></a>
     <a href="<?=BASE_PATH?>admin/changepassword" class="user_button"><?=LNG_CHANGE_PASSWORD?></a>

    </div>
  
</div> </div>

      <div class="extender"></div>