<link href="<?=CSS_URL?>student/admission1.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 

<div id="content-header">
  <img src="<?=IMAGES_URL?>admission/add_school_logo.png">
  <h1><?=LNG_ADD_SCHOOL?></h1>
  <h3><?=LNG_STEP1_SCHOOL_DETAILS?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">

<form method="post" enctype="multipart/form-data" action="<?=BASE_PATH?>school/admission1"><div style="margin:0;padding:0;display:inline"></div>
<div class="box">
<div id="necessary-field-notification"> <?=LNG_FIELDS_MARKED_WITH?> <span class="necessary-field">*</span> <?=LNG_MUST_BE_FILLED?></div>
<div class="label-field-pair">
<label for="configuration_currency_type"><?=LNG_SCHOOL_NAME?> <span class="necessary-field">*</span></label>
<div class="text-input-bg">
<?=$this->Form->institution_name?>
</div>
</div>
<div class="label-field-pair">
<label for="configuration_currency_type"><?=LNG_SCHOOL_ADDRESS?> <span class="necessary-field">*</span></label>
<div class="text-input-bg">
<?=$this->Form->institution_address?>
</div>
</div>
<div class="label-field-pair">
<label for="configuration_currency_type"><?=LNG_SCHOOL_PHONE?> <span class="necessary-field">*</span></label>
<div class="text-input-bg">
<?=$this->Form->institution_phone_no?></div>
</div>

<div class="label-field-pair">
<label for="configuration_currency_type"><?=LNG_SCHOOL_FAX_NO?></label>
<div class="text-input-bg">
<?=$this->Form->institution_fax_no?>
</div>
</div>

<div class="label-field-pair">
<label for="configuration_currency_type"><?=LNG_UPLOAD_LOGO?></label>
<div class="text-input-bg">
<?=$this->Form->student_photo?>
</div>
</div>


<input class="submit_button" type="submit" value="<?=LNG_SAVE?>" name="commit">
</div>

</form></div>

</div> </div>

      <div class="extender"></div>
