
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img alt="Subjects" src="<?=IMAGES_URL?>show_settings.png">
  <h1><?=LNG_BACKUP?></h1>
  <h3><?=LNG_DATABASE_BACKUP?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" class="adminform" >
		<tr>
		  <td valign="top">&nbsp;</td>
		</tr>
		<tr>
		  <td valign="top"></td>
		</tr>
		
		<tr>
		  <td valign="top">&nbsp;</td>
		</tr>
		<? if($this->backup_file_name) { ?>
		<tr>
		  <td valign="top"><?=LNG_BACKUP_STORE_ON?>( <?=BASE_PATH?>data/backups/<?=$this->backup_file_name?> ) </td>
		</tr>
		<? } ?>
		<tr>
		  <td valign="top">&nbsp;</td>
		</tr>
  </table>
</div> </div>

      <div class="extender"></div>
