<link href="<?=CSS_URL?>student_attendance/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 

<div id="content-header">
  <img src="<?=IMAGES_URL?>attendence/attendence.png">
  <h1><?=LNG_ATTENDANCE?></h1>
  <h3><?=LNG_ATTENDANCE_HOME?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>

<div id="page-yield">
  <div id="box">  
  	
		<div class="link-box">
          <div class="link-heading"><a href="<?=BASE_PATH?>attendances"><?=LNG_ATTENDANCE_REGISTER?></a></div>
          <div class="link-descr"><?=LNG_ATTENDANCE_REGISTER_FOR_STUDENTS?></div>
        </div>
		      
        <div class="link-box">
          <div class="link-heading"><a href="<?=BASE_PATH?>attendancereport"><?=LNG_ATTENDANCE_REPORT?></a></div>
          <div class="link-descr"><?=LNG_ATTENDANCE_REPORT_OF_STUDENTS?></div>
        </div>

    <div class="extender"></div>
  </div>


</div> </div>

      <div class="extender"></div>
