<?
global $mySession;
$detail= $this->detail;
?>

<link href="<?=CSS_URL?>reminder/create_reminder.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 



<div id="content-header">
  <img src="<?=IMAGES_URL?>reminder/reminder_small.png">
  <h1>Messages</h1>
  <h3>Send</h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>

<div id="inner-tab-menu">
  <ul>
    
      <li><a href="<?=BASE_PATH?>reminder">Inbox</a></li>
    

    <li><a href="<?=BASE_PATH?>reminder/sentreminder">Sent</a></li>
    <li><a href="<?=BASE_PATH?>reminder/createreminder">Create</a></li>
  </ul>
</div>

<div id="page-yield">

  

  <div class="create-options">
    
  </div>
  
  <div class="extender"></div>

  </div>

</div>

      <div class="extender"></div>
    