<? global $mySession;
$detail= $this->detail;
?>

<link href="<?=CSS_URL?>reminder/index.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>reminder/reminder_small.png">
  <h1>Messages</h1>
  <h3>Inbox</h3>
  <div id="app-back-button">
  <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>

<div id="inner-tab-menu">
  <ul>
    
      <li><a href="<?=BASE_PATH?>reminder"><?=LNG_INBOX?></a></li>
    
    <li><a href="<?=BASE_PATH?>reminder/sentreminder"><?=LNG_SENT?></a></li>
    <li><a href="<?=BASE_PATH?>reminder/createreminder"><?=LNG_CREATE?></a></li>
  </ul>
</div>
<div id="page-yield">
<div id="application-list">
<?

if(is_array($this->viewrem) && count($this->viewrem) > 0) { $viewrem = $this->viewrem[0]; ?>

<?php /*?><table id="listing" width="100%">
  <tbody>
	<tr class="tr-head"><td><?=LNG_FROM?></td><td style="font-weight:normal;"><?=$viewrem['first_name']?>&nbsp;<?=$viewrem['last_name']?></td></tr>
    <tr class="tr-head"><td><?=LNG_TO?></td><td style="font-weight:normal;"><?=$mySession->user['fname']?>&nbsp;<?=$mySession->user['lname']?></td></tr>
    <tr class="tr-head"><td> Date :</td><td style="font-weight:normal;"><?=$viewrem['rdate']?></td></tr>
    <tr class="tr-head"><td> Subject :</td><td style="font-weight:normal;"><?=$viewrem['subject']?></td></tr>
    <tr class="tr-head"><td colspan="2" style="font-weight:normal;padding:50px;"><?=$viewrem['body']?></td></tr>
</tbody></table>
<?php */?>

<link href="<?=CSS_URL?>reminder/view_sent_reminder.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />




<div id="reminder-body">
<div id="reminder-from">From: <?=$viewrem['first_name']?>&nbsp;<?=$viewrem['last_name']?></div>

<div id="reminder-date">Sent on: <?=$viewrem['rdate']?></div>

<div id="reminder-subject">Subject: <?=$viewrem['subject']?></div>



<div id="reminder-message"><strong>Message:</strong> <br><br><?=$viewrem['body']?></div>
</div>



<? 
}
?>
</div>
</div> </div>

      <div class="extender"></div>