
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>examination/show_exam.png" alt="Exam">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_CONSOLIDATED_REPORT?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<?php /*?><div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>exam/consolidated_exam_report_pdf?exam_group=1" target="_blank">PDF Report</a></li>
  </ul>
</div><?php */?>
<div id="page-yield">

  

  
    <h4>BCA | First Test</h4>
    <div class="students-table">
      <table id="listing" align="center" cellpadding="1" cellspacing="1" width="100%">
        <tbody><tr class="tr-head">
          <td><?=LNG_NAME?></td>
          
            <td>002(100.0)</td>
          
          <td><?=LNG_PERCENTAGE?></td> 
        </tr>
        
          <tr class="tr-odd">
            <td class="col-2">Rahul Kumar Sharma</td>
              
                <td class="col-3">
                  
                    100.0
                  
                </td>
            <td class="col-4">
              100.00</td>
          </tr>
        
          <tr class="tr-even">
            <td class="col-2">Ram Kumar </td>
			
                <td class="col-3">
                    -
                </td>

            <td class="col-4">
              </td>
          </tr>
        
      </tbody></table></div>
    <div class="extender"></div>

</div> </div>

      <div class="extender"></div>
    