<?
$examscore = $this->examscore;
?>
      <div id="side_bar">

        <div id="sidebar_news_area">
          
        </div>
      </div>
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>examination/show_exam.png" alt="Exam">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_GENERATED_REPORT?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<?php /*?><div id="inner-tab-menu">
  <ul>
    <li><a href="/exam/generated_report2_pdf?subject_id=1" class="user_button" target="_blank">PDF Report</a></li>
  </ul>
</div><?php */?>

<div id="page-yield">

  

  <div id="box">
    <h4><?=$this->studentinfo[0]['grade_name']?> - <?=$this->studentinfo[0]['batchname']?> | <?=$this->subject[0]['name']?></h4>
    <div id="score-table">
   <?
  tframe_pre();
  ?>
    <table id="listing" cellpadding="1" cellspacing="1" width="100%">
      <tbody><tr class="tr-head">
        <td><?=LNG_NAME?></td>
        
         <? foreach($this->examgroup as $examgroup){ ?>
          <td><?=$examgroup['name']?></td>
        <? } ?>
        
      </tr>
      <?
	  $i= 0;
	  $subjecttotal = array();
	  foreach($this->studentinfo as $studentinfo) {
	  if($i%2) { $class = 'tr-odd';} else { $class = 'tr-even'; }
	  ?>
        <tr class="<?=$class?>">
          <td class="col-2"><?=$studentinfo['name']?></td>
          
             <? foreach($this->examgroup as $examgroup){ 
			  $obt_marks = $examscore[$studentinfo['id']][$examgroup['id']]['marks'];
			  $max_marks = $examscore[$studentinfo['id']][$examgroup['id']]['maxmarks'];
			 
			  $subjecttotal[$examgroup['id']] = $subjecttotal[$examgroup['id']] + $obt_marks;
			  $maxtotal = $maxtotal + $max_marks;
			  $markstotal = $markstotal + $obt_marks;
			 ?>
			  <td><?=$obt_marks.'/'.$max_marks?></td>
			 <? } ?>
          
        </tr>
      <? $i++;
	  } ?>
                 
        
      </tr>
    </tbody></table>
<?
  tframe_post();
  ?>
    </div>
    <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
    