<link href="<?=CSS_URL?>configuration/view_all.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
<script>
function chk_valid()
{
	if(document.getElementById("search_batchid").value=='')
	{
		alert("Please select a class");
		return false;
	}
	return true;
	
	
}
</script>
  <div id="content"> 
<div id="content-header">
  <img alt="Exam" src="<?=IMAGES_URL?>examination/show_exam.png">
  <h1><?=LNG_GENERATE_FINAL_REPORT?></h1>
  <h3><?=LNG_GENERATE_FINAL_REPORT?></h3>
  <div id="app-back-button">
    <a onclick="history.back(); return false;" href="#"><img border="0" src="<?=IMAGES_URL?>buttons/back.png?<?=UPDATE_KEY?>" alt="Back"></a>
  </div>
</div>


<div id="page-yield">
<div class="label-field-pair-select-class" style="width:700px;">
<form action="<?=BASE_PATH?>exam/generatefinal" class="new_subject" id="new_subject" method="post" onsubmit="return chk_valid()">

<label for="student-detail-select-class"><?=LNG_SESSION_START_YEAR?></label>
    <div class="text-input-bg">
	<select name="search_year" id="search_year" onchange="getajax('<?=BASE_PATH?>exam/batchlistcombo/','?search_year='+this.value,'batchlist');">
	<option value=""><?=LNG_SELECT_YEAR?></option>
	<? 
	$yy = date("Y");
	for($i=$yy; $i > ($yy-2); $i--){ ?>	
	<option value="<?=$i?>"><?=$i?></option>
	<? } ?>
	</select></div>
	
	<label for="student-detail-select-class"><?=LNG_SELECT_A_BATCH?></label>
    <div class="text-input-bg" id="batchlist">
	<select name="search_batchid" id="search_batchid">
		<option value=""><?=LNG_SELECT_A_BATCH?></option>
	
	</select></div>
	
	 
	<div class="extender"></div>
	
	
	<label for="student-detail-select-class"><?=LNG_SELECT_SEMESTER?></label>
    <div class="text-input-bg" id="semester">
	<select name="search_semid" id="search_semid">
		<option value="1">Sem 1</option>
		<option value="2">Sem 2</option>	
	</select></div>
 	<div class="submit-button" style="float:left; width:220px">
      <input type="submit" class="submit-button" name="commit" value="<?=LNG_SUBMIT?>">
    </div>
</form>
</div>



 <div id="students"> </div>

</div>

</div>