<?
$db = new Db();
$examscore = $this->examscore;
//echo $mySession->user[0]['usertype'];exit;
?>
<script>
function gotoprint()
{
	obj_win = window.open('about:blank', 'new_win','toolbars=no,maximize=no,scrollbars=yes,menubar=no,width=900,height=680,directories=no,resizable=0,screenX=0,screenY=0,left=0,top=0'  ) ; 
 //alert obj_win;
	obj_win.document.write('<html><title>My School</title><link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" rel="stylesheet" type="text/css" /><head>');

	obj_win.document.write('</head>');
	obj_win.document.write('<style type="text/css">   </style>');
	obj_win.document.write('<body><div style="width:850px; " >');

	obj_win.document.write(document.getElementById('printmiddiv').innerHTML);

	obj_win.document.write("</div></body></html>");

	obj_win.document.close();



	obj_win.focus();

	obj_win.print();

	obj_win.close();
}
</script>

<link href="<?=CSS_URL?>exam/generated_report4.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
<div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>examination/show_exam.png" alt="Exam">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_GROUPED_EXAM_REPORT?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<?php /*?><div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>exam/generated_report4_pdf?student=1" target="_blank">PDF Report</a></li>
  </ul>
</div><?php */?>
<div id="page-yield">
  <div class="submit-button2">
	  <input type="button" value="Print" name="print" class="submit-button" onclick="gotoprint()" />
	  </div>
    <h4 align="center"><? echo $this->studentinfo[0]['grade_name']; ?> - <? echo $this->studentinfo[0]['batchname']; ?></h4>
	 
    <div id="register">      
     <? if($mySession->user['usertype']=='S' || $mySession->user['usertype']=='T') { ?>
	    <div class="header">
			<? if($this->prvnext) { ?>
			<div class="prev">
			  <a href="<?=BASE_PATH?>exam/generatedreport4?student=<?=$this->prv_studentid?>">&lt;</a>
			</div>
			<? 
			} ?>
       
          <div class="month">
            <? echo $this->studentinfo[0]['name']; ?>
          </div>
		  <? if($this->prvnext) { ?>
			<div class="next">
			  <a href="<?=BASE_PATH?>exam/generatedreport4?student=<?=$this->next_studentid?>">&gt;</a>
			</div>
			<? 
			} ?>
         
          <div class="extender"></div>
        </div>
		<? }else{
 	?>
		 <div class="header">
			  <div class="month">
				<? echo $this->studentinfo[0]['name']; ?>
			  </div>
		  <div class="extender"></div>
		  </div>
	<?
 } ?>
    </div>
	
    <div id="score-table">
 <?
  tframe_pre();
  ?>
  <div id="printmiddiv">
	<table id="listing" width="100%">
      <tbody><tr class="tr-head">
        <td><?=LNG_SUBJECT?></td>
        <? foreach($this->examgroup as $examgroup){ ?>
          <td><?=$examgroup['name']?></td>
        <? } ?>
                  
        <td><?=LNG_TOTAL?></td>
      </tr>
      <?
	  $i=1;
	  $markstotal = 0;
	  $maxtotal = 0;
	  foreach($this->subjects as $subjects) {
	  if($i%2) { $class = 'tr-odd';} else { $class = 'tr-even'; }
	  ?>
        <tr class="<?=$class?>">
          <td class="col-2"><?=$subjects['name']?></td>
            
           <?
		    $subjecttotal = 0;
			
		    foreach($this->examgroup as $examgroup){ 
		    $subjecttotal = $subjecttotal+$examscore[$subjects['id']][$examgroup['id']]['marks'];
			$maxtotal = $maxtotal + $examscore[$subjects['id']][$examgroup['id']]['maxmarks'];
			$markstotal = $markstotal + $examscore[$subjects['id']][$examgroup['id']]['marks'];
		   ?>
          	<td class="col-3"><?=$examscore[$subjects['id']][$examgroup['id']]['marks']?> / <?=$examscore[$subjects['id']][$examgroup['id']]['maxmarks']?></td>
        	<? } ?>
		
            <td class="col-1"><?=$subjecttotal?></td>
        </tr>
      <? $i++; 
	  } ?>
       
    </tbody></table>
	</div>
   <?
  tframe_post();
  ?>
    </div>
    
      
      <h4><?=LNG_TOTAL_MARKS?> = <?=$markstotal?>/<?=$maxtotal?> | <?=LNG_AGGREGATE_PERCENT?> = <?=($markstotal/$maxtotal)*100?></h4>
    
    <div class="extender"></div>
 </div> </div>

      <div class="extender"></div>
    