<?
$examscore = $this->examscore;
?>
<script>
function gotoprint()
{
	obj_win = window.open('about:blank', 'new_win','toolbars=no,maximize=no,scrollbars=yes,menubar=no,width=900,height=680,directories=no,resizable=0,screenX=0,screenY=0,left=0,top=0'  ) ; 
 //alert obj_win;
	obj_win.document.write('<html><title>My School</title><link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" rel="stylesheet" type="text/css" /><head>');

	obj_win.document.write('</head>');
	obj_win.document.write('<style type="text/css">   </style>');
	obj_win.document.write('<body><div style="width:850px; " >');

	obj_win.document.write(document.getElementById('printmiddiv').innerHTML);

	obj_win.document.write("</div></body></html>");

	obj_win.document.close();



	obj_win.focus();

	obj_win.print();

	obj_win.close();
}
</script>

<link href="<?=CSS_URL?>exam/generated_report2.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>examination/show_exam.png" alt="Exam">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_GENERATED_REPORT?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<?php /*?><div id="inner-tab-menu">
  <ul>
    <li><a href="/exam/generated_report2_pdf?subject_id=1" class="user_button" target="_blank">PDF Report</a></li>
  </ul>
</div><?php */?>

<div id="page-yield">

  

  <div id="box">
  <div class="submit-button2">
  <input type="button" value="Print" name="print" class="submit-button" onclick="gotoprint()" />
  </div>
    <h4><?=$this->studentinfo[0]['grade_name']?> - <?=$this->studentinfo[0]['batchname']?> | <?=$this->subject[0]['name']?></h4>

    <div id="score-table">
    
<?
  tframe_pre();
  ?>
  <div id="printmiddiv">
	<table id="listing" cellpadding="1" cellspacing="1" width="100%">
      <tbody><tr class="tr-head">
        <td><?=LNG_NAME?></td>
        
         <? foreach($this->examgroup as $examgroup){ ?>
          <td><?=$examgroup['name']?></td>
        <? } ?>
        
      </tr>
      <?
	  $i= 0;
	  $subjecttotal = array();
	  foreach($this->studentinfo as $studentinfo) {
	  if($i%2) { $class = 'tr-odd';} else { $class = 'tr-even'; }
	  ?>
        <tr class="<?=$class?>">
          <td class="col-2"><?=$studentinfo['name']?></td>
          
             <? foreach($this->examgroup as $examgroup){ 
			  $obt_marks = $examscore[$studentinfo['id']][$examgroup['id']]['marks'];
			  $max_marks = $examscore[$studentinfo['id']][$examgroup['id']]['maxmarks'];
			 
			  $subjecttotal[$examgroup['id']] = $subjecttotal[$examgroup['id']] + $obt_marks;
			  $maxtotal = $maxtotal + $max_marks;
			  $markstotal = $markstotal + $obt_marks;
			 ?>
			  <td class="col-4"><?=$obt_marks.'/'.$max_marks?></td>
			 <? } ?>
          
        </tr>
      <? $i++;
	  } ?>
       
      
      <tr class="tr-head">
        <td>
          Class Avg
        </td>
        
            <? foreach($this->examgroup as $examgroup){ ?>
			  <td><?=($subjecttotal[$examgroup['id']]/$i)?></td>
			<? } ?>
          
        
      </tr>
    </tbody></table>
	</div>
<?
  tframe_post();
  ?>	
	
    </div>
    <div class="extender"></div>
  </div>
</div>
 </div>

      <div class="extender"></div>
    