<?
global $mySession;
$examscore = $this->examscore;
//pr($examscore);

?>
<script>
function gotoprint()
{
	obj_win = window.open('about:blank', 'new_win','toolbars=no,maximize=no,scrollbars=yes,menubar=no,width=900,height=680,directories=no,resizable=0,screenX=0,screenY=0,left=0,top=0'  ) ; 
 //alert obj_win;
	obj_win.document.write('<html><title>My School</title><link href="<?=CSS_URL?>student/view_all.css?<?=UPDATE_KEY?>" rel="stylesheet" type="text/css" /><head>');

	obj_win.document.write('</head>');
	obj_win.document.write('<style type="text/css">   </style>');
	obj_win.document.write('<body><div style="width:850px; " >');

	obj_win.document.write(document.getElementById('printmiddiv').innerHTML);

	obj_win.document.write("</div></body></html>");

	obj_win.document.close();



	obj_win.focus();

	obj_win.print();

	obj_win.close();
}
</script>
<link href="<?=CSS_URL?>exam/generated_report.css?<?=UPDATE_KEY?>" media="screen" rel="stylesheet" type="text/css" />
     
      <div id="content"> 
<div id="content-header">
  <img src="<?=IMAGES_URL?>examination/show_exam.png" alt="Exam">
  <h1><?=LNG_EXAMS?></h1>
  <h3><?=LNG_GENERATED_REPORT?></h3>
  <div id="app-back-button">
    <a href="#" onclick="history.back(); return false;"><img alt="Back" src="<?=IMAGES_URL?>buttons/back.png?1313631718" border="0"></a>
  </div>
</div>
<?php /*?><div id="inner-tab-menu">
  <ul>
    <li><a href="<?=BASE_PATH?>exam/consolidatedexamreport?exam_group_id=<?=$this->exam_group_id?>"><?=LNG_CONSOLIDATED_REPORT?></a></li>
     <li><a href="/exam/generatedreportpdf?batch=1&amp;exam_group=1" target="_blank">PDF Report</a></li>
   </ul>
</div><?php */?>
<div id="page-yield">

  
  <div class="box">
  <div class="submit-button2">
	  <input type="button" value="Print" name="print" class="submit-button" onclick="gotoprint()" />
	  </div>
    <h3 align="center"><?=$this->studentinfo[0]['code']?> - <?=$this->studentinfo[0]['batchname']?> - <?=$this->examgroup[0]['name']?></h3>
	
   <?
	if($this->resultpublish==1) {
	?>  
<?
  tframe_pre();
  ?>
	<div id="register">
      
<? if($mySession->user['usertype']=='S' || $mySession->user['usertype']=='T') { ?>
      <div class="header">
        <? if($this->prvnext) { ?>
		<div class="prev">
          <a href="<?=BASE_PATH?>exam/generatedreport?exam_group_id=<?=$this->examgroup[0]['id']?>&amp;student=<?=$this->prv_studentid?>">&lt;</a>
        </div>
		<? 
		} ?>
        <div class="month">
          <?=$this->studentinfo[0]['name']?>
        </div>
		<? if($this->prvnext) { ?>
        <div class="next">
          <a href="<?=BASE_PATH?>exam/generatedreport?exam_group_id=<?=$this->examgroup[0]['id']?>&amp;student=<?=$this->next_studentid?>">&gt;</a>
        </div>
		<? 
		} ?>
        <div class="extender"></div>
      </div>
 <? }else{
 	?>

		 <div class="header">
			<div class="month">
			  <?=$this->studentinfo[0]['name']?>
			</div>
			<div class="extender"></div>
		  </div>

	<?
 } ?>     
    </div>
<?
  tframe_post();
  ?><br />
   
   <?
  tframe_pre();
  ?>
   <div id="printmiddiv">
    <table id="listing" align="center" cellpadding="1" cellspacing="1" width="100%">
      <tbody><tr class="tr-head">
        <td><?=LNG_SUBJECT?></td>
        
          <td><?=LNG_OBTAINED_MARKS?></td>
          <td><?=LNG_MAX_MARKS?></td>
          <td><?=LNG_PERCENTAGE?></td>
        
      </tr>
      <?
	  $totalobt = 0;
	  $totalmax = 0;
	  foreach($this->subjects as $subjects) { 
	  $obt_marks = $examscore[$subjects['id']][$this->examgroup[0]['id']]['marks'];
	  $max_marks = $examscore[$subjects['id']][$this->examgroup[0]['id']]['maxmarks'];
	  $totalobt = $totalobt + $obt_marks;
	  $totalmax = $totalmax + $max_marks;
	  ?>
        <tr class="tr-odd">
          <td class="col-1"><?=$subjects['name']?></td>          
            <td class="col-1"><?=$obt_marks?></td>            
            <td class="col-1"><?=$max_marks?></td>            
            <td class="col-1"><?=($obt_marks/$max_marks)*100?></td>          
        </tr>
      <? } ?>
        <tr class="tr-head">
          <td><?=LNG_TOTAL_MARKS?></td>
          <td><?=$totalobt?></td><td><?=$totalmax?></td>
          
          <td><?=($totalobt/$totalmax)*100?></td>
        </tr>
      
    </tbody></table> 
	</div>
	<?
  tframe_post();
  ?>
	
	<?
	 } else { ?>
	 <div style="padding:0 0 0 35px; font-size:16px; font-weight:600; color:#990A10;"><?=LNG_EXAM_RESULT_NOT_PUBLISHED?> </div>
	 <div class="extender"></div>
	<? } ?>
    <div class="extender"></div> 
  </div>
  
</div>
 </div>

      <div class="extender"></div>
    